### ISSUE TITLE
Problem With Accessibility

### ISSUE THREAD

**Issue by Scientiac** [FunkyMuse/Vigilante#115]
When the Accessibility option is turned un , my phone's volume slider interface doesn't hide automatically
![Screenshot_2021-02-09-22-36-57-899_com brave browser](https://user-images.githubusercontent.com/58177655/107398020-5510e800-6b27-11eb-9ac8-445c8377be3d.jpg)
. Instead It remains there until I touch the screen. This is very annoying , please fix this.
I want stop using it cuzz this app is great , but please fix this issue as soon as you can , Its so annoying.

Device : Redmi note 9 pro max
MIUI 12.0.2.0
Android Version -10

**Comment by FunkyMuse** [comment]
Report this to Xiaomi, this ain't an app problem
