### ISSUE TITLE
Other options blocked on S10+

### ISSUE THREAD

**Issue by veast-mUJ9bDjOlP** [FunkyMuse/Vigilante#119]
![Screenshot_20210211-025639_Vigilante](https://user-images.githubusercontent.com/68193060/107612764-faee5080-6c14-11eb-9a8b-8ce205b4ee1d.jpg)
The corners have buttons/options which are hard to press.

**Comment by FunkyMuse** [comment]
Which version are you using?
Please update to the latest one

**Comment by FunkyMuse** [comment]
If there's no response till the end of the week I'm closing the issue due to inactivity.

**Comment by veast-mUJ9bDjOlP** [comment]
> 
> 
> Which version are you using?
> Please update to the latest one

1.0.9

**Comment by FunkyMuse** [comment]
1.1.0 is the latest release.

https://github.com/FunkyMuse/Vigilante/releases
