### ISSUE TITLE
Cannot uninstall the app.

### ISSUE THREAD

**Issue by OnceUponThisTime** [FunkyMuse/Vigilante#122]
The app offers the possibility to uninstall, yet when I want to press uninstall nothing happens.

Please help, don't want to reset my device to work settings again. 

Thanks in advance.

**Comment by FunkyMuse** [comment]
The app doesn't offer an ability to uninstall, that's f-droid and it's buggy as it seems.

Please see https://github.com/FunkyMuse/Vigilante/issues/71#issuecomment-769303018
