### ISSUE TITLE
Some app icons don't load in the permissions request list 

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#127]

**Comment by FunkyMuse** [comment]
If the app isn't installed anymore the app's icon won't show.

**Comment by shifoc** [comment]
They are still installed.

**Comment by FunkyMuse** [comment]
I guess for some icon can't be extracted :/ 
Can you share a screen?
Also which device you using would be of a big help.

**Comment by FunkyMuse** [comment]
And a version of the app please that'd be of a big help

**Comment by shifoc** [comment]
Version:1.0.9
Phone: Huawei Mate 10 pro
Android 10
![Screenshot_20210223_054018_com.crazylegend.vigilante.jpg](https://user-images.githubusercontent.com/32818143/108799751-be6a0f80-7599-11eb-8893-b862ba657db3.jpg)

**Comment by FunkyMuse** [comment]
Do note that some apps like Reddit etc... don't have consistent icons i.e their icons are changeable either in the app as a user choice or they incorporated same same features without user's need to change it.
