### ISSUE TITLE
Add background permission monitor 

### ISSUE THREAD

**Issue by RAMAR-RAR** [FunkyMuse/Vigilante#128]
Add a option that enable to record use of permission in background(like App permission monitor of Samsung[*Reference](https://www.samsung.com/ae/support/mobile-devices/what-is-this-new-add-feature-app-permission-monitor-and-how-to-turn-off/) )

**Comment by FunkyMuse** [comment]
You already have permission history

**Comment by FunkyMuse** [comment]
Although to note that it works on most devices, maybe it won't work on some heavily changed devices like Oppo, Xiaomi that altered the permissions

**Comment by RAMAR-RAR** [comment]
So Vigilante record this type of request
![20210218_211401](https://user-images.githubusercontent.com/47423745/108415828-4c5a9900-722e-11eb-9717-b5a997597371.jpg) and this one?:
![20210218_211420](https://user-images.githubusercontent.com/47423745/108415905-5d0b0f00-722e-11eb-81ec-6517c4653798.jpg)

**Comment by FunkyMuse** [comment]
Why don't you try it?

**Comment by RAMAR-RAR** [comment]
I tried and works only with first type(Samsung J7)

**Comment by FunkyMuse** [comment]
The second one is tied to OEMs specifics, as I noted above

maybe it won't work on some heavily changed devices like Oppo, Xiaomi that altered the permissions ids in your case Shamesung

**Comment by RAMAR-RAR** [comment]
Ok, It was only a feature that I would like on different devices, but if doesn't work because is a problem based on OEMs restrictions its ok

**Comment by FunkyMuse** [comment]
I don't have a samsung device to make an actual implementation for samsung :D

**Comment by RAMAR-RAR** [comment]
If can help exist an Android Emulator named LDPlayer where can be set model(Windows)

**Comment by FunkyMuse** [comment]
> If can help exist an Android Emulator named LDPlayer where can be set model(OS Windows)(or can be used BlueStacks but I dont remember if can be setted the model)

I use Unix based OS, sorry no love for Windows
