### ISSUE TITLE
Feature request: Option to use the led light instead of a dot on the screen

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#132]

**Comment by FunkyMuse** [comment]
Available in https://github.com/FunkyMuse/Vigilante/releases/tag/1.1.0

**Comment by shifoc** [comment]
It's not working on my phone

**Comment by FunkyMuse** [comment]
I have Huawei Mate 20 pro and it works here

**Comment by FunkyMuse** [comment]
You have to enable notifications under settings...

**Comment by shifoc** [comment]
![Screenshot_20210223_184626_com.huawei.systemmanager.jpg](https://user-images.githubusercontent.com/32818143/108877048-839ec080-7607-11eb-8ccd-ea6dc69ec726.jpg)

What am I doing wrong?

**Comment by FunkyMuse** [comment]
Open the app > settings and check Enable usage notifications

**Comment by shifoc** [comment]
It ![Screenshot_20210223_195348_com.crazylegend.vigilante.jpg](https://user-images.githubusercontent.com/32818143/108885769-dd57b880-7610-11eb-8649-b23ef58f2bee.jpg)
It is already enabled. Also when I disabled dot usage, it was still appearing.

**Comment by FunkyMuse** [comment]
It applies till next restart of the service, don't worry.
It could be a specific issue on the device.

I've tested on Huawei mate 20 pro, Pixel XL 2 and i receive led lights (if i have notifications enabled).

Do you receive LED lights from other apps?
(Also do note that there's sometimes a limit of how many led blinks can be sent and there's nothing we developers can do about it).

**Comment by shifoc** [comment]
Ok I am sorry. What I wanted was for the led light to turn on when the access dot is visible(possibly instead). But I discovered the led blinks when the screen is off only.

**Comment by FunkyMuse** [comment]
> Ok I am sorry. What I wanted was for the led light to turn on when the access dot is visible(possibly instead). But I discovered the led blinks when the screen is off only.

Yes i understand your request and i'm trying to make it work

**Comment by FunkyMuse** [comment]
Apparently this is only available if the screen is off :(
