### ISSUE TITLE
App is not detecting the camera and mic usage anymore. 

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#134]
I tried disabling and enabling the service again but it's still not working.

**Comment by FunkyMuse** [comment]
That won't help me much, device info also videos if it's possible or pics.

**Comment by shifoc** [comment]
> That won't help me much, device info also videos if it's possible or pics.

Huawei mate 10 pro
Android 10
Version 1.1.0


Pic of what, the dot/notification is not appearing when I open the camera

**Comment by FunkyMuse** [comment]
Well you need to enable the service first :)

**Comment by shifoc** [comment]
> Well you need to enable the service first :)

![Screenshot_20210224_190330_com.crazylegend.vigilante.jpg](https://user-images.githubusercontent.com/32818143/109037122-09d40900-76d3-11eb-945f-56c245a2ac0b.jpg)![Screenshot_20210224_190336_com.android.settings.jpg](https://user-images.githubusercontent.com/32818143/109037129-0b9dcc80-76d3-11eb-9979-fe729705749c.jpg)

**Comment by FunkyMuse** [comment]
Did you try restarting the phone?

Did it work before?

**Comment by shifoc** [comment]
Yes it was working before. After restarting my phone it worked again but now it's not working.

**Comment by FunkyMuse** [comment]
Huawei is killing the process, disable all the battery optimizations for the app

**Comment by shifoc** [comment]
> Huawei is killing the process, disable all the battery optimizations for the app

It looks like it fixed the issue for now. Thanks
