### ISSUE TITLE
access logs

### ISSUE THREAD

**Issue by Tin-man-0** [FunkyMuse/Vigilante#153]
Attached should be some bug reports, Also as much as this app is informative and dispays history of notifications and power and headphones. What i don't see is a history of the very thing it's monitoring. You see, while some apps might properly notify you that they are using said permission, others don't. Your app is great in making sure we get notified but the notifications are gone as fast as they can be read. It only takes a few moments of camera time to get a series of pictures and only quick second or two of microphone to pick up high frequency audio queues. So may I suggest a dedicated log made by this app logging the microphone and camera usage as well as speaker usage with as much details as possible because it's just unlikely we're going to catch the app right in the act and be taking screenshots or whatever other logging right when whatever random app crosses the line.

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/73

**Comment by Tin-man-0** [comment]
Even with root privilege? I can't imagine any app can get access to the activity without a name of some kind. Does it just show up like a system process or something?

**Comment by FunkyMuse** [comment]
Yup even with root privilage you can't really do this, you can read what's the currently opened app at the moment but that doesn't necessarily mean that this app is using the camera/mic or started using it
