### ISSUE TITLE
Crashes running bug reports.

### ISSUE THREAD

**Issue by Tin-man-0** [FunkyMuse/Vigilante#154]
_Got this report right after trying to generate a report. also having issues enabling the app. root permission has been granted. _

-----Stack trace----

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 6014952 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:107)
	at k.t.m.g(Unknown Source:31)
	at d.a.i.h.a$a.p(:6)
	at d.a.b.a$a.t(Unknown Source:28)
	at n.o.j.a.a.s(:2)
	at i.a.o0.run(Unknown Source:70)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.TransactionTooLargeException: data parcel size 6014952 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:550)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:288)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:105)
	... 12 more

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 18
Thread time: 0 hr 0 min, 50 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: 6b715c79-9577-4194723-e3439227c87f
Device I
Application version: 9
Default launcher: ch.deletescape.lawnchair.ci
Timezone name: Pacific Standard Time
Timezone ID: America/Los_Angeles
Version release: 11
Version incremental : 1615898726
Version SDK: 30
Board: begonia
Bootloader: unknown
Brand: Redmi
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: begonia
Display: RQ2A.210305.006
Fingerprint: 
Hardware: mt6785
Host: 4c6ca50bd48c
ID: RQ2A.210305.006
Manufacturer: Xiaomi
Product: aosp_begonia
Build time: 1615898626000
Build time formatted: 16-03-2021 05:43:46
Type: user
Radio: MOLY.LR13.R1.TC8.SP.V2.P44,MOLY.LR13.R1.TC8.SP.V2.P44
Tags: release-keys
User: android_build
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 47
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: MT6785V/CC
# of CPU cores: 8
Up time with sleep: 15 hr 34 min, 56 sec
Up time without sleep: 11 hr 20 min, 36 sec

----------- END of Device info -----------

########### Exit reasons ###########

~~~~~~~~~~~ Exit reason #1 ~~~~~~~~~~~

Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 24-03-2021 21:46:56

~~~~~~~~~~~ END of exit reason #1 ~~~~~~~~~~~


 ~~~~~~~~~~~ Exit reason #2 ~~~~~~~~~~~

Description: user request after error
Importance: FOREGROUND
Reason: ANR
Timestamp: 24-03-2021 21:41:54

~~~~~~~~~~~ END of exit reason #2 ~~~~~~~~~~~


 ~~~~~~~~~~~ Exit reason #3 ~~~~~~~~~~~

Description: user request after error
Importance: FOREGROUND
Reason: ANR
Timestamp: 24-03-2021 21:41:28

~~~~~~~~~~~ END of exit reason #3 ~~~~~~~~~~~


########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 9
Version name: 1.1.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 18-03-2021 04:02:08
Last updated: 18-03-2021 04:02:08
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_exclude_vigilante_from_notifications = true, pref_bypass_dnd = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = false

*********** END of Application info ***********


^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^


com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by FunkyMuse** [comment]
This was fixed but the release wasn't published, i will release a new version at the end of the week, it'll come with 1.1.1

**Comment by FunkyMuse** [comment]
I'll keep the issue opened till new version release

**Comment by FunkyMuse** [comment]
1.1.1 was released, please update to the latest version
