### ISSUE TITLE
Unable to configure camera and microphone indicators

### ISSUE THREAD

**Issue by darhma** [FunkyMuse/Vigilante#161]
I installed vigilante version 1.1.1 from f-droid and when I tried to configure the indicators for the camera or microphone it wouldn't show me the configuration screen. I installed the previous version 1.1.0 and I was able to configure everything without problems, I updated to version 1.1.1 and the configuration made is kept but it is not possible to change it.

**Comment by FunkyMuse** [comment]
Would you be able to record a short video of that?

**Comment by FunkyMuse** [comment]
Okay i can see the issue, thanks for reporting it

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/releases/tag/1.1.2

**Comment by darhma** [comment]
Wow that was quick! Thanks, the app is very useful

**Comment by darhma** [comment]
Ok, version 1.1.2 solves the issue. Thanks again
