### ISSUE TITLE
I can't see "Headset connected" I only see "Headset Disconnected" 

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#201]
![Screenshot_20210512_235551_com.crazylegend.vigilante.jpg](https://user-images.githubusercontent.com/32818143/118043131-a37b9000-b37d-11eb-8803-ac2bdc0555c4.jpg)

**Comment by FunkyMuse** [comment]
What device?

**Comment by shifoc** [comment]
Huawei mate 10 pro running on Android 10

**Comment by FunkyMuse** [comment]
This does look like an issue with the implementation on the Huawei side, I haven't been able to replicate this on Huawei mate 20 pro

**Comment by WAPEETY** [comment]
I have the same problem on redmi note 7 with a custom rom (A10) tomorrow I'll check if it's bt headphones problem

**Comment by FunkyMuse** [comment]
> I have the same problem on redmi note 7 with a custom rom (A11) tomorrow I'll check if it's bt headphones problem

Problem with how Xiaomi handles these events, can't do anything about that since I don't have that Xiaomi phone to test it and make a fix
