### ISSUE TITLE
Vibration at OS level disabled after uninstall

### ISSUE THREAD

**Issue by newuser1100** [FunkyMuse/Vigilante#214]
I was testing out whether or not I am able to uninstall the app which I was able to. Along side that though, I was getting no haptic feedback anywhere in my OS (e.g. touch, games that use vibration, etc.). Vibration motor works fine as confirmed through TWRP. Restarted phone, no change. I reinstalled the app, and haptics were restored. I would have first restored my phone but I figured, why is it just this one app with this sort of problem. Must be fixable.

Is the app somehow controlling all and every haptic feedback even after uninstall? 

Device info:
Asus Zenfone 3 running LineageOS

**Comment by FunkyMuse** [comment]
You have an option to disable vibrating

![Screenshot_20210605-101702](https://user-images.githubusercontent.com/25645122/120885079-3ad3ac00-c5e7-11eb-8f2b-17e2aa9c5270.png)

It means whenever your phone gets camera/mic usage it vibrates

**Comment by newuser1100** [comment]
Doesn't answer my question. I asked why is it that once I have uninstalled this app (not any other app, I've tested it), I loose haptic feedback.

**Comment by FunkyMuse** [comment]
The app doesn't control any haptic feedback except the notification one if you've enabled it

**Comment by newuser1100** [comment]
Okay, I believe I have figured it out and it's probably because I'm running custom OS.

I found a workaround. Enabling a second service accessibility option for another app seems to override your app's perms so it starts to work even when the app is uninstalled. Must be an issue from my OS then. Gotta tell Lineage now lol
