### ISSUE TITLE
Delete History

### ISSUE THREAD

**Issue by andreas4491** [FunkyMuse/Vigilante#215]
Is there any way to delete history after x days or select individual items?

**Comment by FunkyMuse** [comment]
There isn't, but there can be.

I'm thinking deleting everything or only X history after 30 days?

Whichever provides better UX

**Comment by andreas4491** [comment]
Sounds good and sensible to me as it looks as if the history file is building up quite quickly and might eventually absorb a lot of storage space.

**Comment by FunkyMuse** [comment]
Yup, I'll reopen the issue till it's implemented

**Comment by andreas4491** [comment]
Sorry, wrong button pressed - mea culpa.
