### ISSUE TITLE
Allow independent activation of camera/mic monitoring or app tagging

### ISSUE THREAD

**Issue by db64** [FunkyMuse/Vigilante#217]
I use an app called PilferShush Jammer to open and hold (lock) the microphone on my device.  Vigilante detects this (properly) and pushes a notification.  However, the notification cannot be dismissed.  The option to have a dot show on the screen when a device is in use shows up for the microphone as well (properly).  However since PJ is holding the microphone open, all I am really looking to monitor is the camera.  Can you separate the microphone and camera monitoring so that they can be independently enabled/disabled?  

Alternatively, and I realize this might be much harder to implement, can you have a method of tagging an app for not notifying?

**Comment by FunkyMuse** [comment]
This will break the whole application if I'm to reimplement everything.

A lot of effort, but yes there can be an app tagging to be removed from notifications just as you exclude Vigilante.

However even this requires tremendous effort which I currently don't have time for.

**Comment by FunkyMuse** [comment]
Also are you talking about app tagging so that a certain app to be excluded for notifications only or for the dots too?

**Comment by db64** [comment]
> Also are you talking about app tagging so that a certain app to be excluded for notifications only or for the dots too?

Yes, that would be the objective.  I am not a programmer, but I know enough about it that I realize that this feature would be very expensive to implement in terms of time and effort.  I only mentioned it in case you might have been working on something similar already. 

My feature request is mainly to keep Vigilante from showing a notification when one is not wanted, while still allowing other notifications.  If that means to disable (what is currently) half the application feature set (e.g. a switch to disable the microphone detection portion), then that fits the request.

If in future you were to implement something fanciful like "location access notifications" or "accellerometer access notifications", then I think an independent switch for each detection feature would be handy.

**Comment by FunkyMuse** [comment]
> > Also are you talking about app tagging so that a certain app to be excluded for notifications only or for the dots too?
> 
> Yes, that would be the objective. I am not a programmer, but I know enough about it that I realize that this feature would be very expensive to implement in terms of time and effort. I only mentioned it in case you might have been working on something similar already.
> 
> My feature request is mainly to keep Vigilante from showing a notification when one is not wanted, while still allowing other notifications. If that means to disable (what is currently) half the application feature set (e.g. a switch to disable the microphone detection portion), then that fits the request.
> 
> If in future you were to implement something fanciful like "location access notifications" or "accellerometer access notifications", then I think an independent switch for each detection feature would be handy.

That makes sense yes, each feature to be toggleable.

I'll see what I can do

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/commit/e397e6a57f0a8f2d014b66cef77ef0cf2f04a415
