### ISSUE TITLE
The location dot is not appearing

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#223]
Version 1.2.1
Android 10
Huawei mate 10 pro

**Comment by FunkyMuse** [comment]
Try turning GPS on and off and see if it'll show

**Comment by shifoc** [comment]
It worked but should it turn on when an apps uses it like camera or only if the gps is on in the settings?

**Comment by FunkyMuse** [comment]
only if the gps is on in the settings

I'm trying to find a way how to make it work when the actual location is used without a permission but idk if it seems feasible.

However the notification is quite explanatory:
Your GPS is enabled, it might be used!

For now that's that.
