### ISSUE TITLE
app crashing when trying to customize

### ISSUE THREAD

**Issue by pokegamer5547** [FunkyMuse/Vigilante#224]
Hi i've just updated to latest version and i noticed when i tap on a notification in notifications list in vigilante it just crashes. I thought maybe it's an compability issue so i cleared app data and did setup again. But this time i noticed i couldn't customize the dots for cam/mic/location. It immediately crashes when i try to do that. (Also crashing when clicking on notification as i mentioned)
Miui 12 android 10 redmi note 9 pro

**Comment by Hippyjake** [comment]
Same issues on pixel 4a stock no root up to date

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/releases/download/1.2.1/vigilante_1.2.1.apk
