### ISSUE TITLE
App crashes when trying to access Dot indicator customizations

### ISSUE THREAD

**Issue by AnonymousSeal** [FunkyMuse/Vigilante#226]
Title says it all

Steps to recreate:
1. Go to settings
2. Click Location, Microphone or Camera
3. Click Dot Indicator

App crashes

Even tried to reinstall it - didn't work either

**Comment by FunkyMuse** [comment]
Download the latest version of the app 

https://github.com/FunkyMuse/Vigilante/issues/224

**Comment by AnonymousSeal** [comment]
I am using v. 1.2.0
Isn't that the latest version?
