### ISSUE TITLE
Vigilante crashes when I try to edit the dot indicator customization

### ISSUE THREAD

**Issue by erfirya** [FunkyMuse/Vigilante#227]
`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:35)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:101)
	... 3 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 15
Thread time: 0 hr 0 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: 32c45437-c4f8-4940-8fd3-3f6389839314
Device ID: ed2b008206fd104b
Application version: 13
Default launcher: com.miui.home
Timezone name: Philippine Standard Time
Timezone ID: Asia/Manila
Version release: 11
Version incremental : V12.0.1.0.RJGMIXM
Version SDK: 30
Board: surya
Bootloader: unknown
Brand: POCO
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: surya
Display: RKQ1.200826.002 release-keys
Fingerprint: POCO/surya_global/surya:11/RKQ1.200826.002/V12.0.1.0.RJGMIXM:user/release-keys
Hardware: qcom
Host: xiaomi.eu
ID: RKQ1.200826.002
Manufacturer: Xiaomi
Product: surya_global
Build time: 1622599502000
Build time formatted: 02-06-2021 10:05:02
Type: user
Radio: MPSS.AT.4.4.c6-00020-RENNELL_GEN_PACK-1,MPSS.AT.4.4.c6-00020-RENNELL_GEN_PACK-1
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 30
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDMMAGPIE
Number of CPU cores: 8
Up time with sleep: 28 hr 30 min, 1 sec
Up time without sleep: 16 hr 45 min, 5 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: bg anr
Importance: FOREGROUND_SERVICE
Reason: ANR
Timestamp: 17-06-2021 06:54:01
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: bg anr
Importance: FOREGROUND_SERVICE
Reason: ANR
Timestamp: 17-06-2021 06:52:53
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 17-06-2021 06:52:26
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 06-04-2021 08:24:41
Last updated: 17-06-2021 06:50:50
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: pref_dot = true, camera_pref_notifications = true, location_pref_dot = true, mic_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, pref_bypass_dnd = false, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, pref_notifications = true
Default prefs: pref_dot = true, camera_pref_notifications = true, location_pref_dot = true, mic_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, pref_bypass_dnd = false, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, pref_notifications = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/224
