### ISSUE TITLE
java.lang.NoSuchMethodException crash when attempting to edit dot indicator appearance

### ISSUE THREAD

**Issue by Peppernose145** [FunkyMuse/Vigilante#228]
# Info
Version: 1.2.0
Obtained from: F-Droid
Device Model: Essential PH-1
Android Version: Android 10, LineageOS for MicroG 17.1

# To reproduce:

1. Open Vigilante
2. Open the settings screen.
3. Click anything in the *Customization* group
4. Click *Dot indicator*
5. This will crash the app

# Additional Info
It appears there were similar issues in the past which have been closed. The bug is present, whether it was always present, or only came back in this update.

Closed issues related:
#226 
#227 
#224 

# Crash Report
`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	... 3 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 24
Thread time: 0 hr 0 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: 9cc77034-bab1-4fcc-bb2f-b03d255fb5aa
Device ID: b650f0618c2bfd57
Application version: 13
Default launcher: com.teslacoilsw.launcher
Timezone name: Pacific Standard Time
Timezone ID: America/Los_Angeles
Version release: 10
Version incremental : eng.root.20201205.155456
Version SDK: 29
Board: Mata
Bootloader: mata-84f7cce
Brand: essential
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: mata
Display: lineage_mata-userdebug 10 QQ3A.200805.001 eng.root.20201205.155456 dev-keys
Fingerprint: essential/mata/mata:8.1.0/OPM1.180104.092/224:user/release-keys
Hardware: mata
Host: 7f38b591c4c5
ID: QQ3A.200805.001
Manufacturer: Essential Products
Product: mata
Build time: 1607183633000
Build time formatted: 05-12-2020 07:53:53
Type: user
Radio: 2.0.c4-M2.0.5
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 84
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: Qualcomm Technologies, Inc MSM8998
Number of CPU cores: 8
Up time with sleep: 166 hr 15 min, 23 sec
Up time without sleep: 73 hr 1 min, 6 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 24-04-2021 09:25:09
Last updated: 17-06-2021 04:07:52
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: pref_dot = true, pref_bypass_dnd = true, location_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, location_pref_notifications = true, pref_date = MM/dd/yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = false, location_pref_bypass_dnd = false
Default prefs: pref_dot = true, pref_bypass_dnd = true, location_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, location_pref_notifications = true, pref_date = MM/dd/yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = false, location_pref_bypass_dnd = false

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/224

**Comment by Peppernose145** [comment]
Okay, apparently this is not the latest version. Why hasn't it been updated on F-Droid? #224

**Comment by FunkyMuse** [comment]
Because f-droid is slow
