### ISSUE TITLE
Customizing the dots crashes the apl

### ISSUE THREAD

**Issue by e-magon** [FunkyMuse/Vigilante#235]
Hi. I updated the app from F-Droid but now it will crash everytime I try to open the setting to customize the usage dots.
I tried to delete all the app data but it still crashes.

Thank you and sorry if the bug was already reported, I didn't find it in the issues.

`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	... 3 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 15
Thread time: 0 hr 0 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: 17c1e0f1-2e6b-4e4b-9813-ed2393d6591b
Device ID: 964c0d6fbc314d2f
Application version: 13
Default launcher: com.sec.android.app.launcher
Timezone name: Central European Standard Time
Timezone ID: Europe/Rome
Version release: 11
Version incremental : N975FXXU7FUE3
Version SDK: 30
Board: exynos9825
Bootloader: N975FXXU7FUE3
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: d2s
Display: RP1A.200720.012.N975FXXU7FUE3
Fingerprint: samsung/d2seea/d2s:11/RP1A.200720.012/N975FXXU7FUE3:user/release-keys
Hardware: exynos9825
Host: 21DJF601
ID: RP1A.200720.012
Manufacturer: samsung
Product: d2seea
Build time: 1620355332000
Build time formatted: 07-05-2021 04:42:12
Type: user
Radio: N975FXXU7FUE1,N975FXXU7FUE1
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_MODERATE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 35
Battery remaining time: 01-01-1970 01:00:00
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 1 hr 56 min, 47 sec
Up time without sleep: 1 hr 25 min, 22 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 16-05-2021 22:03:31
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 12-05-2021 11:15:37
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 12-05-2021 11:15:30
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 15-04-2021 02:24:51
Last updated: 17-06-2021 14:42:53
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, location_pref_dot = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false, location_pref_bypass_dnd = false
Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, location_pref_dot = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false, location_pref_bypass_dnd = false

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/224
