### ISSUE TITLE
Crashes after 1.2.1 update. 

### ISSUE THREAD

**Issue by Peaceseeker-starterpack** [FunkyMuse/Vigilante#236]
Hi,

Lately i having some few crashes after 1.2.1 version update. I highly sus it has to do with the show dot "Location" usage. By disabling it and it work perfectly fine for now. 

Btw, i love your app. Thank you for doing what you are doing. :)

`` Stacktrace ``

java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2077)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:705)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:346)
	at android.view.accessibility.AccessibilityRecord.getSource(AccessibilityRecord.java:189)
	at com.crazylegend.vigilante.service.VigilanteService.onAccessibilityEvent(:6)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1635)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1824)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$AppWidgetManagerLocal.getHostedWidgetPackages(AppWidgetServiceImpl.java:4808)
	at com.android.server.accessibility.AccessibilityManagerService$SecurityPolicy.computeValidReportedPackages(AccessibilityManagerService.java:3387)
	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.findAccessibilityNodeInfoByAccessibilityId(AbstractAccessibilityServiceConnection.java:596)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:312)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 15
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: 167b7843-f761-4b2c-94fc-50a3e335eeb8
Device ID: f85ec437fd74b8e0
Application version: 14
Default launcher: android
Timezone name: Malaysia Time
Timezone ID: Asia/Kuala_Lumpur
Version release: 10
Version incremental : 00WW_4_15N
Version SDK: 29
Board: SDM660
Bootloader: unknown
Brand: Nokia
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: B2N_sprout
Display: 00WW_4_15N
Fingerprint: Nokia/Onyx_00WW/B2N_sprout:10/QKQ1.190828.002/00WW_4_15N:user/release-keys
Hardware: qcom
Host: cm-build-42-110-5050
ID: QKQ1.190828.002
Manufacturer: HMD Global
Product: Onyx_00WW
Build time: 1615197972000
Build time formatted: 08-03-2021 18:06:12
Type: user
Radio: MPSS.AT.3.1-00822_GEN_PACK-1.245278.1.262738.2
Tags: release-keys
User: cm
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_ALL_DISABLED_WHEN_SCREEN_OFF
Is device idle: No
Battery percentage: 61
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM660
Number of CPU cores: 8
Up time with sleep: 12 hr 2 min, 0 sec
Up time without sleep: 5 hr 6 min, 43 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 14
Version name: 1.2.1
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 17-06-2021 07:09:49
Last updated: 17-06-2021 07:09:49
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = false, mic_pref_bypass_dnd = false, location_pref_dot = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en
Default prefs: camera_pref_notifications = false, mic_pref_bypass_dnd = false, location_pref_dot = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
location_pref_dot = false

So it isn't caused by the location 🙂

**Comment by Peaceseeker-starterpack** [comment]
hah, you were right FunkyMuse ;p 

despite the show Location dot disable or enable, i'm still having the crashes. 

Peace. 

![Screenshot_20210618-175414](https://user-images.githubusercontent.com/86084623/122545742-c4ac5c00-d060-11eb-95d0-b8572db60b22.png)

`` Stacktrace ``

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5106)
    at android.view.ViewGroup.addView(ViewGroup.java:4935)
    at android.view.ViewGroup.addView(ViewGroup.java:4875)
    at android.view.ViewGroup.addView(ViewGroup.java:4848)
    at c.a.i.o.a.o.a(:1)
    at com.crazylegend.vigilante.service.VigilanteService$a.e(:8)
    at com.crazylegend.vigilante.location.LocationProcessor$a$a.u(:11)
    at com.crazylegend.vigilante.location.LocationProcessor$a$a.l(:3)
    at n.a.m2.w.u(Unknown Source:48)
    at n.a.m2.w.k(:1)
    at n.a.m2.z0.k$a$a.u(:2)
    at n.a.m2.z0.k$a$a.l(:2)
    at n.a.c.p0(:4)
    at c.d.a.j.b0(:4)
    at n.a.m2.z0.k$a$b.a(Unknown Source:111)
    at n.a.m2.k0.c(:4)
    at n.a.m2.k0$b.u(Unknown Source:12)
    at m.n.j.a.a.s(:2)
    at n.a.o0.run(Unknown Source:86)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7397)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 29
Thread time: 0 hr 0 min, 37 sec

`` END of thread info ``

`` Device info ``

Report ID: 8c6aba88-273f-4aa2-bfc8-f70c4c1d755c
Device ID: f85ec437fd74b8e0
Application version: 14
Default launcher: com.android.launcher3
Timezone name: Malaysia Time
Timezone ID: Asia/Kuala_Lumpur
Version release: 10
Version incremental : 00WW_4_15N
Version SDK: 29
Board: SDM660
Bootloader: unknown
Brand: Nokia
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: B2N_sprout
Display: 00WW_4_15N
Fingerprint: Nokia/Onyx_00WW/B2N_sprout:10/QKQ1.190828.002/00WW_4_15N:user/release-keys
Hardware: qcom
Host: cm-build-42-110-5050
ID: QKQ1.190828.002
Manufacturer: HMD Global
Product: Onyx_00WW
Build time: 1615197972000
Build time formatted: 08-03-2021 18:06:12
Type: user
Radio: MPSS.AT.3.1-00822_GEN_PACK-1.245278.1.262738.2
Tags: release-keys
User: cm
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_ALL_DISABLED_WHEN_SCREEN_OFF
Is device idle: No
Battery percentage: 35
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM660
Number of CPU cores: 8
Up time with sleep: 24 hr 26 min, 10 sec
Up time without sleep: 13 hr 43 min, 47 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 14
Version name: 1.2.1
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 17-06-2021 07:09:49
Last updated: 17-06-2021 07:09:49
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = false, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en
Default prefs: camera_pref_notifications = false, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en

`` END of Application info ``


`` Currently running foreground/background processes ``


com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by m-rey** [comment]
Can confirm that this also happens on a Xiaomi Redmi Note 10 Pro (also called "tucana") running ProjectSakura 4.R, which is based on LineageOS 18.1. The Android version is 11.  I'm running version 1.2.0 of Vigilante and encountered the same crash. 

# steps to replicate
Vigilante crashes when a "dot indicator" entry is pressed in customization settings. It doesn't matter if it's the one for the camera, microphone, or location. The crash occurs, no matter if other options on the same config list view or vigilante itself are enabled or not.  
The previous 

I've also deleted the cache, then storage, then tried reinstalling and granting the necessary permissions again, but no luck. I've rechecked after every step if it still crashes and was able to replicate the crash every time.


# Stacktrace

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	... 3 more
```


# Thread info

```
Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 17
Thread time: 0 hr 0 min, 1 sec
```


# Device info

```
Report ID: aff909b8-4969-4f92-a8ff-de106660ce37
Device ID: c34aae5b83856fe3
Application version: 13
Default launcher: com.teslacoilsw.launcher
Timezone name: Central European Standard Time
Timezone ID: Europe/Berlin
Version release: 11
Version incremental : eng.cakest.20210118.162003
Version SDK: 30
Board: tucana
Bootloader: unknown
Brand: Xiaomi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: tucana
Display: RQ1A.210105.003
Fingerprint: google/redfin/redfin:11/RQ1A.210205.004/7038034:user/release-keys
Hardware: qcom
Host: b450aorusm
ID: RQ1A.210105.003
Manufacturer: Xiaomi
Product: lineage_tucana
Build time: 1610979529000
Build time formatted: 18-01-2021 15:18:49
Type: user
Radio: 4.3.c5-00052-1016_1620_ad4ee45,4.3.c5-00052-1016_1620_ad4ee45
Tags: release-keys
User: cakestwix
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 30
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: Qualcomm Technologies, Inc SM7150
Number of CPU cores: 8
Up time with sleep: 26 hr 47 min, 41 sec
Up time without sleep: 21 hr 13 min, 53 sec
```


# Exit reasons

## Exit reason #1
```
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 18-06-2021 09:28:17
```


## Exit reason #2
```
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 18-06-2021 09:18:01
```


## Exit reason #3
```
Description: stop com.crazylegend.vigilante due to from pid 13720
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 18-06-2021 09:17:38
```


# Application info

```
App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 13-02-2021 22:30:14
Last updated: 17-06-2021 02:38:40
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false
Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false
```


# Currently running foreground/background processes
N/A

**Comment by FunkyMuse** [comment]
> Can confirm that this also happens on a Xiaomi Redmi Note 10 Pro (also called "tucana") running ProjectSakura 4.R, which is based on LineageOS 18.1. The Android version is 11. I'm running version 1.2.0 of Vigilante and encountered the same crash.
> # steps to replicate
> 
> Vigilante crashes when a "dot indicator" entry is pressed in customization settings. It doesn't matter if it's the one for the camera, microphone, or location. The crash occurs, no matter if other options on the same config list view or vigilante itself are enabled or not.
> The previous
> 
> I've also deleted the cache, then storage, then tried reinstalling and granting the necessary permissions again, but no luck. I've rechecked after every step if it still crashes and was able to replicate the crash every time.
> # Stacktrace
> 
> ```
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 	... 1 more
> Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
> 	at java.lang.Class.getMethod(Class.java:2072)
> 	at java.lang.Class.getMethod(Class.java:1693)
> 	at j.r.f.getValue(:3)
> 	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
> 	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
> 	at j.m.b.h0.f(:11)
> 	at j.m.b.h0.k(:8)
> 	at j.m.b.a0.B(:19)
> 	at j.m.b.a0.W(Unknown Source:91)
> 	at j.m.b.a0.z(:4)
> 	at j.m.b.a0$d.run(Unknown Source:3)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:223)
> 	at android.app.ActivityThread.main(ActivityThread.java:7660)
> 	... 3 more
> ```
> 
> # Thread info
> 
> ```
> Name: main
> ID: 2
> State: RUNNABLE
> Priority: 5
> Thread group name: main
> Thread group parent: system
> Thread group active count: 17
> Thread time: 0 hr 0 min, 1 sec
> ```
> 
> # Device info
> 
> ```
> Report ID: aff909b8-4969-4f92-a8ff-de106660ce37
> Device ID: c34aae5b83856fe3
> Application version: 13
> Default launcher: com.teslacoilsw.launcher
> Timezone name: Central European Standard Time
> Timezone ID: Europe/Berlin
> Version release: 11
> Version incremental : eng.cakest.20210118.162003
> Version SDK: 30
> Board: tucana
> Bootloader: unknown
> Brand: Xiaomi
> CPU ABIS 32: armeabi-v7a, armeabi
> CPU ABIS 64: arm64-v8a
> Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
> Device: tucana
> Display: RQ1A.210105.003
> Fingerprint: google/redfin/redfin:11/RQ1A.210205.004/7038034:user/release-keys
> Hardware: qcom
> Host: b450aorusm
> ID: RQ1A.210105.003
> Manufacturer: Xiaomi
> Product: lineage_tucana
> Build time: 1610979529000
> Build time formatted: 18-01-2021 15:18:49
> Type: user
> Radio: 4.3.c5-00052-1016_1620_ad4ee45,4.3.c5-00052-1016_1620_ad4ee45
> Tags: release-keys
> User: cakestwix
> User IDs: N/A
> Is sustained performance mode supported: Yes
> Is in power save mode: No
> Is in interactive state: Yes
> Is ignoring battery optimizations: Yes
> Thermal status: STATUS_NONE
> Location power save mode: MODE_NO_CHANGE
> Is device idle: No
> Battery percentage: 30
> Battery remaining time: N/A
> Is battery charging: No
> Is device rooted: Yes
> CPU Model: Qualcomm Technologies, Inc SM7150
> Number of CPU cores: 8
> Up time with sleep: 26 hr 47 min, 41 sec
> Up time without sleep: 21 hr 13 min, 53 sec
> ```
> 
> # Exit reasons
> ## Exit reason #1
> 
> ```
> Description: crash
> Importance: FOREGROUND
> Reason: CRASH
> Timestamp: 18-06-2021 09:28:17
> ```
> 
> ## Exit reason #2
> 
> ```
> Description: crash
> Importance: FOREGROUND
> Reason: CRASH
> Timestamp: 18-06-2021 09:18:01
> ```
> 
> ## Exit reason #3
> 
> ```
> Description: stop com.crazylegend.vigilante due to from pid 13720
> Importance: CACHED
> Reason: USER_REQUESTED
> Timestamp: 18-06-2021 09:17:38
> ```
> 
> # Application info
> 
> ```
> App name: Vigilante
> Version code: 13
> Version name: 1.2.0
> Package name: com.crazylegend.vigilante
> Short package name: app
> Flavor: N/A
> Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
> Is debuggable: No
> First installed: 13-02-2021 22:30:14
> Last updated: 17-06-2021 02:38:40
> Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
> Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false
> Default prefs: camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false
> ```
> 
> # Currently running foreground/background processes
> 
> N/A

Update to 1.2.1 from GitHub, f-droid is slow

**Comment by FunkyMuse** [comment]
Main issue crashes at

`ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference`

Not related to the app, this is a system error

**Comment by m-rey** [comment]
Thanks for taking a look! Just saw the release notification.
Seems to work fine again on version 1.2.1 from github
