### ISSUE TITLE
f-droid inclusion

### ISSUE THREAD

**Issue by FunkyMuse** [FunkyMuse/Vigilante#24]

**Comment by CraZyLegenD** [comment]
The issue lives on
https://gitlab.com/fdroid/rfp/-/issues/1555

**Comment by IzzySoft** [comment]
And I hope you won't rename yourself too often. Several links were invalidated (redirects do not always work). Your new homepage seems not to be up yet?

**Comment by FunkyMuse** [comment]
> And I hope you won't rename yourself too often. Several links were invalidated (redirects do not always work). Your new homepage seems not to be up yet?

The previous nickname was really old so i thought I'd change it.

Soon everything will be up, just changed it.

And no I won't be renaming anytime soon.

**Comment by IzzySoft** [comment]
OK, I better not tell you how old my nick is then. Only so much: it's not from this millenium… :rofl:

**Comment by FunkyMuse** [comment]
> OK, I better not tell you how old my nick is then. Only so much: it's not from this millenium… rofl

Yours does age like wine, but mine was rather childish.

**Comment by pokegamer5547** [comment]
@FunkyMuse Ah is there any way of contact you directly?like email or something. I have some questions to ask privately about the app?😅

**Comment by FunkyMuse** [comment]
> @FunkyMuse Ah is there any way of contact you directly?like email or something. I have some questions to ask privately about the app?sweat_smile

You have [discussions](https://github.com/FunkyMuse/Vigilante/discussions)

**Comment by IzzySoft** [comment]
It's live now, congrats! But before you close this issue, please fix fastlane: it must be `fastlane/metadata/android/en-US` – the `android` level is currently missing, and thus no summary, description etc. showing up at F-Droid. Once done, it should ship to F-Droid with your next release being tagged (and fetched).

**Comment by FunkyMuse** [comment]
> It's live now, congrats! But before you close this issue, please fix fastlane: it must be `fastlane/metadata/android/en-US` – the `android` level is currently missing, and thus no summary, description etc. showing up at F-Droid. Once done, it should ship to F-Droid with your next release being tagged (and fetched).
> 
> PS: Shall I keep your app in my repo, now that it's on "F-Droid proper"? I'd suggest to keep it until your description etc is fixed (so at least people who have my repo enabled get that). Once that's fixed, it's up to you; if your release cycle is higher than F-Droid's, it might be a good idea to keep it with mine – otherwise… well, up to you. Originally I removed apps from my repo then unless someone insisted I shall keep it, meanwhile it's almost 50:50.

[Fixed in 1.0.6](https://github.com/FunkyMuse/Vigilante/releases/tag/1.0.6)

Do as you think it's better, now that the description is fixed, is it?
If so... everyone need to get it I think.

**Comment by IzzySoft** [comment]
Thanks!

It will take a few days until the fix made it to the index. From that day, I'd wait another 2..3 days (so it can propagate), then unlist it at my end. If you want it back for any reason, just yell – it's easily re-established as I just "archive" metadata.

**Comment by FunkyMuse** [comment]
> Thanks!
> 
> It will take a few days until the fix made it to the index. From that day, I'd wait another 2..3 days (so it can propagate), then unlist it at my end. If you want it back for any reason, just yell – it's easily re-established as I just "archive" metadata.

Sure, if you can just send the link once it's available on f-droid to include it into the readme so that people can download it, i'd appreciate it a lot.

**Comment by IzzySoft** [comment]
The link will be `https://f-droid.org/packages/<packageName>/` as usual :smiley:

**Comment by FunkyMuse** [comment]
https://f-droid.org/packages/com.crazylegend.vigilante
