### ISSUE TITLE
crash while changing settings

### ISSUE THREAD

**Issue by berlin46** [FunkyMuse/Vigilante#240]
Steps to reproduce 
Setting>camera >dot indicator>crash 

`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	... 3 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 23
Thread time: 0 hr 0 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: f9f1a1ef-e2aa-484b-ac32-acd73d6aee0c
Device ID: a80db661b2aa6ca7
Application version: 13
Default launcher: com.google.android.apps.nexuslauncher
Timezone name: India Standard Time
Timezone ID: Asia/Kolkata
Version release: 11
Version incremental : 1621409170
Version SDK: 30
Board: sdm845
Bootloader: unknown
Brand: Xiaomi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: beryllium
Display: RQ2A.210505.003
Fingerprint: Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V12.0.2.0.QEJMIXM:user/release-keys
Hardware: qcom
Host: 7c9349601839
ID: RQ2A.210505.003
Manufacturer: Xiaomi
Product: beryllium
Build time: 1621409074000
Build time formatted: 19-05-2021 12:54:34
Type: user
Radio: 4.0.c2.6-00335-1227_1222_40a1464,4.0.c2.6-00335-1227_1222_40a1464
Tags: release-keys
User: android_build
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 15
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM845
Number of CPU cores: 8
Up time with sleep: 37 hr 33 min, 56 sec
Up time without sleep: 25 hr 31 min, 9 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 19-06-2021 08:45:03
Last updated: 19-06-2021 08:45:03
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_delete_history = false, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true
Default prefs: camera_pref_notifications = true, pref_delete_history = false, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Version name: 1.2.0

Update to 1.2.1 from GitHub, please use search next time when opening an issue
