### ISSUE TITLE
Mute notification sound? 

### ISSUE THREAD

**Issue by edent** [FunkyMuse/Vigilante#242]
I love the pop up telling me the camera is in use. Is it possible to turn off the notification sound though?

Thanks - great app.

**Comment by FunkyMuse** [comment]
You can disable the notification in settings, but you won't receive notification...

**Comment by nurullahsaeem** [comment]
> You can disable the notification in settings, but you won't receive notification...
> 
> Are you asking for a feature to be added?
> Like an option to disable sound when notification is sent to you?

I would love to have that

**Comment by FunkyMuse** [comment]
This will be available in the 1.2.2 release
