### ISSUE TITLE
Camera notification settings override microphone notification settings

### ISSUE THREAD

**Issue by AnonymousSeal** [FunkyMuse/Vigilante#244]
To recreate:
1. Activate both camera and microphone notifications
2. Disable microphone notifications
3. return to general settings page
4. go back to microphone settings - microphone notifications are still on

2nd way:
1. Activate both camera and microphone notifications
2. Disable camera notifications
3. return to general settings page
4. go to microphone settings - microphone notifications are off too

___

Doesn't happen with location. If I were to guess I'd say this might be because the app had only a general notification toggle before the update and camera and microphone still use the general notification setting.

**Comment by FunkyMuse** [comment]
Thank you, I'll look into this

**Comment by FunkyMuse** [comment]
Will be available in 1.2.2 release, thank you for reporting it.
