### ISSUE TITLE
Vigilante Crash

### ISSUE THREAD

**Issue by capitalstep** [FunkyMuse/Vigilante#247]
Application crashes while trying to adjust location alert settings.

`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	... 3 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 12
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: 4b02fe03-38a9-4504-9b4c-b1fdfdc4d08f
Device ID: fd54712b818185e0
Application version: 13
Default launcher: com.microsoft.launcher
Timezone name: Eastern Standard Time
Timezone ID: America/New_York
Version release: 11
Version incremental : N970USQS6FUE3
Version SDK: 30
Board: msmnile
Bootloader: N970USQS6FUE3
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: d1q
Display: RP1A.200720.012.N970USQS6FUE3
Fingerprint: samsung/d1qsq/d1q:11/RP1A.200720.012/N970USQS6FUE3:user/release-keys
Hardware: qcom
Host: 21DJ7D15
ID: RP1A.200720.012
Manufacturer: samsung
Product: d1qsq
Build time: 1621324623000
Build time formatted: 18-05-2021 03:57:03
Type: user
Radio: N970USQS6FUE3
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 27
Battery remaining time: 31-12-1969 19:00:00
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SM8150
Number of CPU cores: 8
Up time with sleep: 3 hr 38 min, 16 sec
Up time without sleep: 1 hr 37 min, 33 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 21-06-2021 20:57:48
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 21-06-2021 17:20:08
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 21-06-2021 09:14:42
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 09-05-2021 21:25:30
Last updated: 19-06-2021 13:24:47
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: pref_dot = true, pref_bypass_dnd = true, location_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = false, pref_biometric_auth = false, location_pref_bypass_dnd = false
Default prefs: pref_dot = true, pref_bypass_dnd = true, location_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = false, pref_biometric_auth = false, location_pref_bypass_dnd = false

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Update to 1.2.1
