### ISSUE TITLE
Crash on dot indicator customization

### ISSUE THREAD

**Issue by vectorlit** [FunkyMuse/Vigilante#248]
Attempting to tap the "dot indicator customization" option in settings for any setting causes the app to crash.

Dot indicator does not appear when using permissions, but the app notification does appear.

Service is enabled and allowed. Samsung Note 20 Ultra 5G.

Only occurs in 1.20, does not occur in 1.13. Downgrading for now has solved my issue.

`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	... 3 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 19
Thread time: 0 hr 0 min, 1 sec

`` END of thread info ``

`` Device info ``

Report ID: 7989d653-5858-47fe-ae57-af22ad68249d
Device ID: a3797f26f176af40
Application version: 13
Default launcher: com.sec.android.app.launcher
Timezone name: Mountain Standard Time
Timezone ID: America/Denver
Version release: 11
Version incremental : N986USQS2DUE2
Version SDK: 30
Board: kona
Bootloader: N986USQS2DUE2
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: c2q
Display: RP1A.200720.012.N986USQS2DUE2
Fingerprint: samsung/c2qsqw/c2q:11/RP1A.200720.012/N986USQS2DUE2:user/release-keys
Hardware: qcom
Host: 21DJGD06
ID: RP1A.200720.012
Manufacturer: samsung
Product: c2qsqw
Build time: 1621425339000
Build time formatted: 19-05-2021 05:55:39
Type: user
Radio: N986USQS2DUE2
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_LIGHT
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 76
Battery remaining time: 31-12-1969 17:00:00
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc KONA
Number of CPU cores: 8
Up time with sleep: 233 hr 41 min, 7 sec
Up time without sleep: 71 hr 24 min, 17 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 13
Version name: 1.2.0
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 22-06-2021 12:00:38
Last updated: 22-06-2021 12:00:38
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = false, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false
Default prefs: camera_pref_notifications = false, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Do not open tickets for the same issue all over again.

Too tired, search for the fix.
