### ISSUE TITLE
Crushed on Poco X2

### ISSUE THREAD

**Issue by Orkpo** [FunkyMuse/Vigilante#251]
`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at j.t.m.F(Unknown Source:33)
	at c.a.i.o.a.o.f(Unknown Source:16)
	at com.crazylegend.vigilante.service.VigilanteService$a.f(:2)
	at c.a.i.u.a.onRecordingConfigChanged(:3)
	at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2970)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 30
Thread time: 0 hr 3 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: 7dd1cbab-57ac-49ea-b1de-d28eb183c2da
Device ID: 7d51455c0be3c21c
Application version: 14
Default launcher: com.mi.android.globallauncher
Timezone name: Bangladesh Standard Time
Timezone ID: Asia/Dhaka
Version release: 11
Version incremental : V12.1.5.0.RGHINXM
Version SDK: 30
Board: phoenixin
Bootloader: unknown
Brand: POCO
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: phoenixin
Display: RKQ1.200826.002 test-keys
Fingerprint: POCO/phoenixin/phoenixin:11/RKQ1.200826.002/V12.1.5.0.RGHINXM:user/release-keys
Hardware: qcom
Host: c5-miui-ota-bd106.bj
ID: RKQ1.200826.002
Manufacturer: Xiaomi
Product: phoenixin
Build time: 1623678030000
Build time formatted: 14-06-2021 19:40:30
Type: user
Radio: 4.3.c5-00100-0524_1101_04aa332,4.3.c5-00100-0524_1101_04aa332
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 59
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SM7150
Number of CPU cores: 8
Up time with sleep: 18 hr 30 min, 38 sec
Up time without sleep: 7 hr 42 min, 59 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: SwipeUpClean
Importance: CACHED
Reason: OTHER
Timestamp: 25-06-2021 16:48:44
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: SwipeUpClean
Importance: CACHED
Reason: OTHER
Timestamp: 25-06-2021 16:40:39
`` END of exit reason #2 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 14
Version name: 1.2.1
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 25-06-2021 16:37:10
Last updated: 25-06-2021 16:37:10
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true, Locale.Helper.Selected.Language = en, pref_language = en
Default prefs: pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true, Locale.Helper.Selected.Language = en, pref_language = en

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Please update to 1.2.2

**Comment by Orkpo** [comment]
> Please update to 1.2.2

But version 1.2.2 isn't available on F-droid

**Comment by Orkpo** [comment]
> Please update to 1.2.2

![Screenshot_2021-06-26-00-53-40-805_org.fdroid.fdroid.jpg](https://user-images.githubusercontent.com/56797263/123472437-fef59a80-d618-11eb-8883-2d6c8c758a68.jpg)[]()

**Comment by FunkyMuse** [comment]
It's available on GitHub

**Comment by Orkpo** [comment]
Thanks
