### ISSUE TITLE
Location dot usage not showing

### ISSUE THREAD

**Issue by david-lev** [FunkyMuse/Vigilante#253]
I have Samsubg galaxy S21, android 11. Accessibility permissions granted to the app and the camera and microphone dots works, but the location indication didn't.

I went into the Google Maps app, for example. And the location icon appear at the top bar, but the dot didn't shows up. 
It is interesting to note that in some cases the dot appears regardless of the location services, which do not work. Just forcing the app to stop removes the point from the screen.

What can I do to fix this problem?

**Comment by FunkyMuse** [comment]
The dot appears when you enable GPS, to detect when gps is used it's impossible, the dot is just like a reminder that your GPS is enabled and can be used by some apps

**Comment by david-lev** [comment]
> The dot appears when you enable GPS, to detect when gps is used it's impossible, the dot is just like a reminder that your GPS is enabled and can be used by some apps

Oh.
So you may want to change the description from "You'll see a dot appear on your screen when usage happens" to something else.

Anyway, thanks for your amazing app!

**Comment by FunkyMuse** [comment]
It's described in the notification you get

**Comment by FunkyMuse** [comment]
But you're right, I'll change it
