### ISSUE TITLE
Sometimes the notification doesn't go away after the camera or mic is stopped being used

### ISSUE THREAD

**Issue by shifoc** [FunkyMuse/Vigilante#296]
![Screenshot_20210829_125200.jpg](https://user-images.githubusercontent.com/32818143/131246268-1880943b-649d-4842-bce8-21edf86b568d.jpg)

**Comment by FunkyMuse** [comment]
Which phone?

When does that happen?

Does it happen always?

Is there another application using accessibility service?

**Comment by shifoc** [comment]
> Which phone?
> Huawei Mate 10 pro
> When does that happen?
> randomly after using the cam or mic
> Does it happen always?
> No
> Is there another application using accessibility service?
Yes:
Notification History and Access Dots

**Comment by FunkyMuse** [comment]
> > Which phone?
> > Huawei Mate 10 pro
> > When does that happen?
> > randomly after using the cam or mic
> > Does it happen always?
> > No
> > Is there another application using accessibility service?
> > Yes:
> > Notification History and Access Dots

Then there's the issue, some of those apps are holding the camera/mic longer than Vigilante
