### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by val-2** [FunkyMuse/Vigilante#302]
The app crashed while in background. After the crash, dots and notifications didn't pop up until I manually disabled and enabled the app service in accessibility settings or restarted the phone. Just opening the app didn't restore functionality.
This specific crash happened more than once. All crash reports had the same stacktrace.

`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at g.a.l.b.h(Unknown Source:33)
	at g.a.o.o.a.t.f(Unknown Source:16)
	at com.crazylegend.vigilante.service.VigilanteService$a.b(:2)
	at g.a.o.g.a$a.t(:3)
	at m.n.j.a.a.s(:2)
	at n.a.o0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 23
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: 1aff8f62-52d7-4d00-b63c-2236ec973c3e
Device ID: 5ff533dce7525af7
Application version: 16
Default launcher: com.teslacoilsw.launcher
Timezone name: Central European Standard Time
Timezone ID: Europe/Rome
Version release: 10
Version incremental : G965FXXUGFUG4
Version SDK: 29
Board: exynos9810
Bootloader: G965FXXUGFUG4
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: star2lte
Display: QP1A.190711.020.G965FXXUGFUG4
Fingerprint: samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUGFUG4:user/release-keys
Hardware: samsungexynos9810
Host: SWDH7021
ID: QP1A.190711.020
Manufacturer: samsung
Product: star2ltexx
Build time: 1627371308000
Build time formatted: 27-07-2021 09:35:08
Type: user
Radio: G965FXXUGFUG4,G965FXXUGFUG4
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 57
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 13 hr 30 min, 40 sec
Up time without sleep: 10 hr 4 min, 35 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 16
Version name: 1.2.3
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 22-02-2021 22:57:39
Last updated: 22-08-2021 11:02:36
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = false, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en, mic_pref_sound = true
Default prefs: camera_pref_notifications = false, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en, mic_pref_sound = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Is this crash happening only on one device?

I can't reproduce it.

**Comment by val-2** [comment]
I didn't test it on other devices, only on my Samsung S9+. At the moment of the crash the app was also excluded from battery optimisations, so in theory Samsung aggressive RAM management isn't at fault.

**Comment by FunkyMuse** [comment]
Please if possible test it on another device, if the same behavior happens I can investigate further, otherwise I'm afraid it might be device's bad implementation of a certain Android API

**Comment by FunkyMuse** [comment]
Due to inactivity I'm closing the issue for the time being.
