### ISSUE TITLE
App stops randomly. Crash reports are too long to copy.

### ISSUE THREAD

**Issue by sync1211** [FunkyMuse/Vigilante#318]
While using the app it randomly stops every few weeks. 
I've been unable to reproduce this crash so far.
Whenever I try to copy the crash report I get a message, telling me that the text was too long and could not be copied.

**Comment by FunkyMuse** [comment]
Could be a device problem, since you can't reproduce it I can't help you since I'll probably be unable to do so myself, sorry.
