### ISSUE TITLE
Volume dialog takes 15 seconds to dismiss when Vigilante service activated

### ISSUE THREAD

**Issue by dealaney** [FunkyMuse/Vigilante#327]
Lately I discovered my volume slider takes a bit longer to dismiss. Disabling and enabling  all apps that uses the accessibility service showed Vigilante is the only service that causes it.

This is not a major issue for me but I'll be happy if I could find a fix for it.

I read potential causes of it here;

https://www.xda-developers.com/why-android-phone-volume-dialog/amp/

Thank you for this wonderful app.

Device: Realme 3
OS ver: Android 10

-D

**Comment by FunkyMuse** [comment]
Will produce a release this weekend
