### ISSUE TITLE
[Feature Request] Disable temporarily usage warnings

### ISSUE THREAD

**Issue by yagueto** [FunkyMuse/Vigilante#340]
It would be useful to be able to stop notification and dot warnings temporarily. For example, if I'm trying to record a video, it's annoying to get a notification sound over it. 

A way around this could be using [android's action tiles](https://medium.com/androiddevelopers/quick-settings-tiles-e3c22daf93a8), so that it's easy and fast to activate and deactivate the warnings, instead of disabling and enabling the accessibility service every time.

BTW, thanks for the great app!

**Comment by FunkyMuse** [comment]
You can disable them in settings

**Comment by yagueto** [comment]
> You can disable them in settings

Yeah, I know, but I find the notificafions helpful so I just want to disable it for a moment. That's why I think it's useful to have a tile action where I can set it to enabled / disabled easily

**Comment by FunkyMuse** [comment]
You can't do that, the tile would be a shortcut to the settings where you'd still need to disable the service manually
