### ISSUE TITLE
Logs not working

### ISSUE THREAD

**Issue by Halilb1978** [FunkyMuse/Vigilante#342]
Vigilante working fine while showing if camera or location enabled. But it stopped showing notification, power ... histories. Accessibility , background power usage ,background data usage, background data usage while data saving on are enabled; not in battery saving mode. What else i can do for logs working. I added the crash report.

`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at g.a.l.b.h(Unknown Source:33)
	at g.a.o.o.a.t.f(Unknown Source:16)
	at com.crazylegend.vigilante.service.VigilanteService$a.b(:2)
	at g.a.o.g.a$a.t(:3)
	at m.n.j.a.a.s(:2)
	at n.a.o0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 24
Thread time: 0 hr 19 min, 48 sec

`` END of thread info ``

`` Device info ``

Report ID: 6164eef8-5047-4ee4-be5c-9b12c8951b32
Device ID: c7c3139a442e4070
Application version: 16
Default launcher: com.sec.android.app.launcher
Timezone name: GMT+03:00
Timezone ID: Europe/Istanbul
Version release: 11
Version incremental : A505FDDU9CUH3
Version SDK: 30
Board: exynos9610
Bootloader: A505FDDU9CUH3
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: a50
Display: RP1A.200720.012.A505FDDU9CUH3
Fingerprint: samsung/a50dd/a50:11/RP1A.200720.012/A505FDDU9CUH3:user/release-keys
Hardware: exynos9610
Host: VPDJR210
ID: RP1A.200720.012
Manufacturer: samsung
Product: a50dd
Build time: 1629189627000
Build time formatted: 17-08-2021 11:40:27
Type: user
Radio: A505FXXU9CUH1
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_GPS_DISABLED_WHEN_SCREEN_OFF
Is device idle: No
Battery percentage: 94
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 23 hr 14 min, 12 sec
Up time without sleep: 9 hr 39 min, 53 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 29-07-2021 17:05:13
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 02-09-2021 11:50:36
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: bg anr
Importance: FOREGROUND_SERVICE
Reason: ANR
Timestamp: 01-09-2021 17:43:26
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 16
Version name: 1.2.3
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 19-07-2021 23:48:03
Last updated: 07-08-2021 14:20:41
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true
Default prefs: camera_pref_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Does it happen often?

Seems like a problem that happens rarily

**Comment by Halilb1978** [comment]
Vigilante last release is 31.10.2021. I probably updated at 01.11.2021. And my last logs are 01.11.2021. It looks like i have no new logs in last release

**Comment by FunkyMuse** [comment]
Try version 1.2.4 and if you don't have the crashes or it doesn't crash often and only once in a while, blame Shamesung

**Comment by Halilb1978** [comment]
I am already using 1.2.4. 1.2.3 were working perfect. 1.2.4 working for notifications of cam,loc..  usage. But 1.2.4 not showing and history. My last history logs are from 1.2.3.

**Comment by FunkyMuse** [comment]
> I am already using 1.2.4. 1.2.3 were working perfect. 1.2.4 working for notifications of cam,loc.. usage. But 1.2.4 not showing and history. My last history logs are from 1.2.3. Btw i just saw the log file i copied here says 1.2.3 but on phone it is 1.2.4

Try restarting your phone, sounds stupid foreal but sometimes it's the solution.

**Comment by Halilb1978** [comment]
I could not explain well. I am using 1.2.4 till 01.11.2021. No history till 12 days. In that time i restarted phone many times. I also uninstalled and reinstalled app again. Still no new history. If it was a phone related matter i guess 1.2.3 would have same matter.

**Comment by FunkyMuse** [comment]
> I could not explain well. I am using 1.2.4 till 01.11.2021. No history till 12 days. In that time i restarted phone many times. I also uninstalled and reinstalled app again. Still no new history. If it was a phone related matter i guess 1.2.3 would have same matter.

You have to enable history in settings now

**Comment by Halilb1978** [comment]
All enabled.
