### ISSUE TITLE
Vigilante accessibility service not working

### ISSUE THREAD

**Issue by erfirya** [FunkyMuse/Vigilante#344]
`` Stacktrace ``

java.lang.IllegalStateException: View android.widget.LinearLayout{535426d V.E...... ......I. 0,0-0,0 #7f0a01d4 app:id/root} has already been added to the window manager.
	at android.view.WindowManagerGlobal.addView(Unknown Source:110)
	at android.view.WindowManagerImpl.addView(Unknown Source:26)
	at com.crazylegend.vigilante.service.VigilanteService.onServiceConnected(:1)
	at android.accessibilityservice.AccessibilityService.dispatchServiceConnected(Unknown Source:34)
	at android.accessibilityservice.AccessibilityService.access$100(Unknown Source:0)
	at android.accessibilityservice.AccessibilityService$2.onServiceConnected(Unknown Source:2)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(Unknown Source:327)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(Unknown Source:4)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 12
Thread time: 0 hr 0 min, 1 sec

`` END of thread info ``

`` Device info ``

Report ID: 13d71b1a-b1ba-4bea-b454-fe6731a3a505
Device ID: ed2b008206fd104b
Application version: 17
Default launcher: com.teslacoilsw.launcher
Timezone name: Philippine Standard Time
Timezone ID: Asia/Manila
Version release: 11
Version incremental : V12.5.3.0.RJGMIXM
Version SDK: 30
Board: surya
Bootloader: unknown
Brand: POCO
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: surya
Display: RKQ1.200826.002 release-keys
Fingerprint: POCO/surya_global/surya:11/RKQ1.200826.002/V12.5.3.0.RJGMIXM:user/release-keys
Hardware: qcom
Host: xiaomi.eu
ID: RKQ1.200826.002
Manufacturer: Xiaomi
Product: surya_global
Build time: 1634128546000
Build time formatted: 13-10-2021 20:35:46
Type: user
Radio: MPSS.AT.4.4.c6-00037-4.426211.1.427267.1,MPSS.AT.4.4.c6-00037-4.426211.1.427267.1
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 95
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDMMAGPIE
Number of CPU cores: 8
Up time with sleep: 81 hr 25 min, 36 sec
Up time without sleep: 33 hr 13 min, 10 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: stop com.crazylegend.vigilante due to installPackageLI
Importance: FOREGROUND_SERVICE
Reason: USER_REQUESTED
Timestamp: 06-08-2021 06:48:33
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: SwipeUpClean
Importance: CACHED
Reason: OTHER
Timestamp: 09-11-2021 08:12:08
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 09-11-2021 08:12:04
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 17
Version name: 1.2.4
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 21-06-2021 21:59:08
Last updated: 01-11-2021 08:18:25
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_lockscreen = true, pref_date = MM-dd-yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_lockscreen = true, pref_date = MM-dd-yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_exclude_vigilante_from_notifications = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by erfirya** [comment]
Been like this for weeks now

**Comment by erfirya** [comment]
![IMG_20211114_211223](https://user-images.githubusercontent.com/71990871/141682542-721bebc5-bb2f-4c7a-b7f1-6169e22b3d89.jpg)
![IMG_20211114_211151](https://user-images.githubusercontent.com/71990871/141682547-58a2bdb8-4c14-41ac-a0bf-8e16559eb0e8.jpg)
![IMG_20211114_211125](https://user-images.githubusercontent.com/71990871/141682548-dbfe488f-480a-4c86-a872-250d4cdb6238.jpg)
![IMG_20211114_211105](https://user-images.githubusercontent.com/71990871/141682550-c2a74659-30ec-4815-913b-cc1efdef15b3.jpg)

**Comment by FunkyMuse** [comment]
Can you try reinstalling the app, try install it from GitHub instead of fdroid

**Comment by erfirya** [comment]
I've already tried this and after a reboot it works. But then after sometime its just not working again for no reason at all. Battery optimization is already turned off for vigilante.

**Comment by FunkyMuse** [comment]
I have poco F3 and can't reproduce it man, sorry.
