### ISSUE TITLE
Notification dots stay on the screen 

### ISSUE THREAD

**Issue by bbw22** [FunkyMuse/Vigilante#366]
All three notification dots remain on the screen even after the usage has stopped. The dots can only be removed with a reboot, and return as soon as anything being monitored is activated. The problem started with the Android 12 upgrade. Device: Pixel 4A (5G) running Android 12.

**Comment by FunkyMuse** [comment]
I'm running Pixel 6 Pro, Android 12, can't reproduce the issue, are you running a custom ROM?

**Comment by FunkyMuse** [comment]
Did you try stopping the application from the accessibility service and trying to enable it again?

**Comment by bbw22** [comment]
No. So I just tried it. Magically the dots went away. Restarted the service. No dots. Turn on the camera. The dot comes up. Stop using the camera. The dot stays. I can try to see if the mic and GPS dots also stay, but suspect they do. At least now a I know a reboot isn't required to remove the dots. I'm happy to try something else.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by FunkyMuse** [comment]
The accessibility service is bugged then, glad it helped.
