### ISSUE TITLE
Ability to filter out empty notifications

### ISSUE THREAD

**Issue by istudyatuni** [FunkyMuse/Vigilante#384]
Hello! I think it would be a good idea to add the ability to disable saving notifications if it's empty, such as this, because there are quite a few

![Screenshot_20211231-195802.png](https://user-images.githubusercontent.com/43654815/147834042-77b747be-27ef-429e-af9a-9ec5f863f964.png)

Radio toggle in settings, or something like this

Thanks :)

**Comment by FunkyMuse** [comment]
You can disable saving notifications totally, although I'm not sure why anyone would send an empty notification at all, are they empty to begin with or the app doesn't pick the content?

**Comment by istudyatuni** [comment]
I think that these notifications are initially empty, because I do not see them, they, as I understand it, are immediately deleted. Sometimes there is more than one notification in a row

<details>

![Screenshot_20220101-105245.png](https://user-images.githubusercontent.com/43654815/147846469-a95f0451-23b6-4bf8-911c-4242e5637ef3.png)

</details>

My phone: Pixel 5A with December 2021 update
