### ISSUE TITLE
Permissions wrong information

### ISSUE THREAD

**Issue by pokegamer5547** [FunkyMuse/Vigilante#39]
I tried testing this app by removing camera permission to my stock camera app and for some reason it registered as 
Settings got removed camera permission. 
And when I opened camera app and it asked for permission, I accepted the permission and the app registered it as 
Lawn chair (my phone launcher) got camera permission. 
![Screenshot_2020-12-08-12-41-37-885_com crazylegend vigilante](https://user-images.githubusercontent.com/65234485/101451807-c3cc9c00-3952-11eb-98a3-4270b3104799.jpg)

**Comment by FunkyMuse** [comment]
There's a slight delay untill Android broadcasts the next package that's currently requesting something, it's barely fixable and unpredictable, although the app can register settings permissions approval and denial from stock settings (aosp).
