### ISSUE TITLE
Dot obscured by screen corner

### ISSUE THREAD

**Issue by jcxmt125** [FunkyMuse/Vigilante#41]
When I enable dots for camera, the dot is partially hidden when in fullscreen. Screenshot doesn't seem to reflect this.

**Comment by FunkyMuse** [comment]
Can you post a screenshot?

**Comment by naturale0** [comment]
I have the same issue.

![Screenshot](https://user-images.githubusercontent.com/22269411/102251734-8e264500-3f48-11eb-812e-34e17a39c65d.png)

**Comment by FunkyMuse** [comment]
Alright, thank you for your description, I'll see what it's the best thing to do about rounded displays but it seems to me that an option to add custom margins is the best that's gonna be.

**Comment by naturale0** [comment]
Thanks. Besides custom margin, how about adding alternative dot location (top center) to the option? It might be the way to avoid the issue too.

**Comment by FunkyMuse** [comment]
> Thanks. Besides custom margin, how about adding alternative dot location (top center) to the option? It might be the way to avoid the issue too.

Yeah, awesome suggestion too, I'll leave this issue open just in case someone else recommends something too

**Comment by FunkyMuse** [comment]
This issue can be resolved by https://github.com/FunkyMuse/Vigilante/issues/57
@naturale0 what do you think?

**Comment by naturale0** [comment]
I agree as well. Thanks.
