### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [FunkyMuse/Vigilante#411]
Hi, this issue has relation with #408

When executing this sequence of actions, there is a loss of data in the activity MainActivity:

1. TouchEvent	[[360,457],[720,815]]
2. DoubleRotationEvent	
3. KeyEvent(name=BACK)	
4. KeyEvent(name=BACK)	
5. IntentEvent(intent='am start com.crazylegend.vigilante/com.crazylegend.vigilante.MainActivity')	
6. TouchEvent	[[360,457],[720,815]]
7. TouchEvent	[[14,68],[93,147]]
8. TouchEvent	[[360,1173],[720,1558]]
9. **Cap01**: capture screen properties before rotation
10. DoubleRotationEvent
11. **Cap02**: capture screen properties after rotation

Cap01 != Cap02 (lost several properties)

We found other flaws in MainActivity: lost fragment, expanded list element and lost activity state.

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159144469-3a960e9d-6ecd-45f8-a596-cdee338d9e16.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159144468-7aa22914-553d-4440-8ed7-3b5e0f532802.png" width=20% height=20%>
</figure>

</div> 

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

**Comment by FunkyMuse** [comment]
Fixed, will come in new release
