### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by marudhasundar** [FunkyMuse/Vigilante#413]
`` Stacktrace ``

java.lang.RuntimeException: Unable to stop service com.crazylegend.vigilante.service.VigilanteService@2cdc4bf: java.lang.IllegalArgumentException: View=android.widget.LinearLayout{1558fca V.E...... ......I. 0,0-0,0 #7f0a01d4 app:id/root} not attached to window manager
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4562)
	at android.app.ActivityThread.access$2300(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.IllegalArgumentException: View=android.widget.LinearLayout{1558fca V.E...... ......I. 0,0-0,0 #7f0a01d4 app:id/root} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:556)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:460)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:138)
	at com.crazylegend.vigilante.service.VigilanteService.onDestroy(:13)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4542)
	... 8 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 13
Thread time: 0 hr 0 min, 1 sec

`` END of thread info ``

`` Device info ``

Report ID: 57658e66-1f0d-463c-a7ec-a20b6c415a24
Device ID: 2f07dccd09bc864b
Application version: 17
Default launcher: net.oneplus.launcher
Timezone name: India Standard Time
Timezone ID: Asia/Kolkata
Version release: 11
Version incremental : 2202112155
Version SDK: 30
Board: msmnile
Bootloader: unknown
Brand: OnePlus
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OnePlus7
Display: GM1901_14_220211
Fingerprint: OnePlus/OnePlus7/OnePlus7:11/RKQ1.201022.002/2202112155:user/release-keys
Hardware: qcom
Host: rd-build-79
ID: RKQ1.201022.002
Manufacturer: OnePlus
Product: OnePlus7
Build time: 1644588070000
Build time formatted: 11-02-2022 19:31:10
Type: user
Radio: 1.1-00007-SM8150_GEN_PACK-2.387049.1.399262.2
Tags: release-keys
User: OnePlus
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_ALL_DISABLED_WHEN_SCREEN_OFF
Is device idle: No
Battery percentage: 75
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SM8150
Number of CPU cores: 8
Up time with sleep: 36 hr 34 min, 44 sec
Up time without sleep: 12 hr 11 min, 58 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: VISIBLE
Reason: CRASH
Timestamp: 25-03-2022 16:03:13
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: empty #32
Importance: CACHED
Reason: OTHER
Timestamp: 24-03-2022 18:51:36
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: empty #31
Importance: CACHED
Reason: OTHER
Timestamp: 24-03-2022 15:32:26
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 17
Version name: 1.2.4
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 19-03-2022 10:42:09
Last updated: 19-03-2022 10:42:09
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = true, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, pref_exclude_vigilante_from_notifications = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = true, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, pref_exclude_vigilante_from_notifications = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Does this happen often?

**Comment by FunkyMuse** [comment]
Will close due to inactivity, reply again in the future to the previous question so that I'll reopen it.
