### ISSUE TITLE
Permissions history, power history, headset history, etc never display anything.

### ISSUE THREAD

**Issue by TinyAtoms** [FunkyMuse/Vigilante#432]
When clicking Permissions, power, headset, notification or lockscreen history, , I always see "There are no results chief, try coming back later, we'll keep looking".
Even after I've just gotten a notification that an app is using camera/location/some permission. I have no idea what headset and power history are supposed to show.

Device info:
Phone: Onneplus 7
OS: Android 12L (well, the latest DerpFest ROM for my phone)
Rooted: yes
No idea which info you need, exactly.

**Comment by FunkyMuse** [comment]
I can not reproduce this, on neither of my phones.

**Comment by NoJustAnother** [comment]
I am facing the same issue. Samsung M31, not rooted. How to '_enable the permission logging inside settings._'? I have enabled it in accessibility. (The setting which opens when we click on 'Enable'). Just like @TinyAtoms, the notifications for camera, microphone, etc. are working fine.

**Comment by FunkyMuse** [comment]
I forgot to mention that permission logging doesn't work on all devices

**Comment by remi975** [comment]
Hello,

I'm having the exact same problem (There are no results chief...) on a Samsung s10e and a Samsung a32. Vigilante 1.2.4 installed from f-droid. None of the phone are rooted, notifications work fine.

Rémi

**Comment by FunkyMuse** [comment]
Try on AOSP phones

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/releases/tag/1.2.5
