### ISSUE TITLE
Loss of history logging after update to 1.2.4

### ISSUE THREAD

**Issue by Gissyup4** [FunkyMuse/Vigilante#434]
Non rooted on Android 10

The app still notifies when permissions are requested, but there is no history recorded in any of the categories (power, notifications, lock screen...) past the date the update was performed.

Would like to perform adb data backup and reinstall app, but android:allowBackup="false" in manifest.

**Comment by FunkyMuse** [comment]
The backup is removed due to security reasons as to nothing leaves the app

**Comment by Gissyup4** [comment]
> The backup is removed due to security reasons as to nothing leaves the app

So I guess I have no choice but to lose the data?

**Comment by FunkyMuse** [comment]
Thanks, I'll look into it

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/432

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/releases/tag/1.2.5
