### ISSUE TITLE
stops working after 10-15minutes in background

### ISSUE THREAD

**Issue by anaysharma** [FunkyMuse/Vigilante#446]
its stopped working after putting app in background, no battery optimisation, locked from memory clean up, all permissions allowed, still.
have tried reinstalling many times, still no different in usability.

My device:
POCO X2
MIUI 12.7.2 on Android 11

**Comment by FunkyMuse** [comment]
Blame it on Xiaomi, disable everything you have for power optimizations, I have Poco F3 and can't reproduce it, the moment you wrote the issue I put it to test, so it's been around 40 minutes and it's working.

https://dontkillmyapp.com/ this might help you
