### ISSUE TITLE
Feature Request: App and Provider Information

### ISSUE THREAD

**Issue by Saijin-Naib** [FunkyMuse/Vigilante#447]
![Screenshot_20220517-072002.png](https://user-images.githubusercontent.com/19295950/168799669-3d16ff8b-11ad-46fe-9fe6-4bea9f5fc237.png)

Currently, the notification tells me that a Provider is being used, but not what is using that provider. It isn't always obvious which app is using a given provider, especially when some run in the background.

Similarly, I'd love to see a log section in the app for the Providers and what app requested them, like we have for Permissions, etc.

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/73
