### ISSUE TITLE
Restricted setting

### ISSUE THREAD

**Issue by timesword3d** [FunkyMuse/Vigilante#512]
Pixel 4, Android 13

![Screenshot_20220910-105107](https://user-images.githubusercontent.com/79085810/189491278-05392f36-b5ff-413e-b108-07d5c2e301c1.png)

**Comment by FunkyMuse** [comment]
Did you install it from f-droid or GitHub?

**Comment by timesword3d** [comment]
f-droid

**Comment by FunkyMuse** [comment]
Does the same thing happen when you install from GitHub?

**Comment by timesword3d** [comment]
Same exact thing after uninstalling and then installing the github apk

**Comment by FunkyMuse** [comment]
1. On your Android device, open the Settings app.
2. Tap Apps.
3. Tap the app that you want to turn on a restricted setting for.
        Tip: If you can't find it, first tap See all apps or App info.
4. Tap More and then Allow restricted settings.
5. Follow the on-screen instructions.

**Comment by FunkyMuse** [comment]
Also update to 1.2.7 for Android 13 support
