### ISSUE TITLE
Dot doesn't show on screen despite open "Show dot usage"

### ISSUE THREAD

**Issue by beam2546** [FunkyMuse/Vigilante#52]
This is my first time submit issue on GitHub so not sure if I do it right or not. Feel free to tell me if you need more information.

Device info
- POCO F2 Pro
- Xiaomi.eu rom (V12.2.1.0.RJKCNXM)
- Rooted with Magisk + Enable MagiskHide (Dot still doesn't show in non-root)

Already try
- Disable and enable show dot usage again
- Disable and enable app again
- Restart app
- Reinstall app

This seem to work fine on my Mi A1 with LOS.

**Comment by FunkyMuse** [comment]
It may be specific to poco phones, someone else has to try with the same model and let us know?

**Comment by FunkyMuse** [comment]
Since it's been 10 days and no answer, I'm closing the issue
