### ISSUE TITLE
App isn't running properly on MIUI 13.0.12

### ISSUE THREAD

**Issue by asim-sansi** [FunkyMuse/Vigilante#540]
`` Stacktrace ``

java.lang.RuntimeException: Unable to stop service com.crazylegend.vigilante.service.VigilanteService@85615ff: java.lang.IllegalArgumentException: View=android.widget.LinearLayout{a167fdf V.E...... ......I. 0,0-0,0 #7f0a01e7 app:id/root} not attached to window manager
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4560)
	at android.app.ActivityThread.access$2100(ActivityThread.java:261)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2062)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8163)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalArgumentException: View=android.widget.LinearLayout{a167fdf V.E...... ......I. 0,0-0,0 #7f0a01e7 app:id/root} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:572)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:476)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:139)
	at com.crazylegend.vigilante.service.VigilanteService.onDestroy(SourceFile:13)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4535)
	... 8 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 15
Thread time: 0 hr 0 min, 1 sec

`` END of thread info ``

`` Device info ``

Report ID: 335c5e5f-1caa-4f93-8f34-4fa38c4eec39
Device ID: 32d4da7b2e45b6cc
Application version: 19
Default launcher: com.miui.home
Timezone name: Pakistan Standard Time
Timezone ID: Asia/Karachi
Version release: 11
Version incremental : V13.0.12.0.RGEMIXM
Version SDK: 30
Board: fog
Bootloader: unknown
Brand: Redmi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: fog
Display: RKQ1.211001.001 test-keys
Fingerprint: Redmi/fog_global/fog:11/RKQ1.211001.001/V13.0.12.0.RGEMIXM:user/release-keys
Hardware: qcom
Host: m1-xm-ota-bd289.bj.idc.xiaomi.com
ID: RKQ1.211001.001
Manufacturer: Xiaomi
Product: fog_global
Build time: 1664455123000
Build time formatted: 29-09-2022 17:38:43
Type: user
Radio: MPSS.HA.1.1.c1-00019-KD_ALL_PACK-2,MPSS.HA.1.1.c1-00019-KD_ALL_PACK-2
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 55
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SM6225
Number of CPU cores: 8
Up time with sleep: 100 hr 50 min, 27 sec
Up time without sleep: 45 hr 2 min, 34 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: OneKeyClean
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 18-10-2022 18:25:39
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: AutoLockOffClean
Importance: VISIBLE
Reason: OTHER
Timestamp: 07-10-2022 01:06:20
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: OneKeyClean
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 05-10-2022 05:17:27
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 19
Version name: 1.2.6
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 16-08-2022 10:39:46
Last updated: 16-08-2022 10:39:46
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = true, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = true, location_pref_bypass_dnd = true, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, pref_delete_history = false, camera_pref_bypass_dnd = true, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = true, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = true, location_pref_bypass_dnd = true, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, pref_delete_history = false, camera_pref_bypass_dnd = true, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
hard to reproduce
