### ISSUE TITLE
Accessibility is malfunctioning 

### ISSUE THREAD

**Issue by vineeth-motati** [FunkyMuse/Vigilante#561]
`` Stacktrace ``

java.lang.IllegalStateException: View android.widget.LinearLayout{993edac V.E...... ......I. 0,0-0,0 #7f0a01e7 app:id/root} has already been added to the window manager.
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:111)
	at com.crazylegend.vigilante.service.VigilanteService.onServiceConnected(SourceFile:1)
	at android.accessibilityservice.AccessibilityService.dispatchServiceConnected(AccessibilityService.java:728)
	at android.accessibilityservice.AccessibilityService.access$100(AccessibilityService.java:234)
	at android.accessibilityservice.AccessibilityService$2.onServiceConnected(AccessibilityService.java:2071)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2312)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 12
Thread time: 0 hr 0 min, 3 sec

`` END of thread info ``

`` Device info ``

Report ID: f3beceac-ab50-4e76-ab96-30857122542e
Device ID: 4fdfd918fd9edaa9
Application version: 19
Default launcher: com.teslacoilsw.launcher
Timezone name: India Standard Time
Timezone ID: Asia/Kolkata
Version release: 11
Version incremental : V12.5.2.0.RCOINXM
Version SDK: 30
Board: ginkgo
Bootloader: unknown
Brand: xiaomi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: ginkgo
Display: RKQ1.201004.002 test-keys
Fingerprint: Redmi/begonia_eea/begonia:11/RP1A.200720.011/V12.5.2.0.RGGEUXM:user/release-keys
Hardware: qcom
Host: m1-xm-ota-bd104.bj.idc.xiaomi.com
ID: RKQ1.201004.002
Manufacturer: Xiaomi
Product: ginkgo
Build time: 1655469372000
Build time formatted: 17-06-2022 18:06:12
Type: user
Radio: .1-00270-NICOBAR_GEN_PACK-1.433714.1.435199.1,.1-00270-NICOBAR_GEN_PACK-1.433714.1.435199.1
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 45
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: Qualcomm Technologies, Inc TRINKET
Number of CPU cores: 8
Up time with sleep: 500 hr 38 min, 40 sec
Up time without sleep: 171 hr 27 min, 38 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: SwipeUpClean
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 17-01-2023 23:37:11
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: SwipeUpClean
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 17-01-2023 22:22:07
`` END of exit reason #2 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 19
Version name: 1.2.6
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 17-01-2023 22:06:46
Last updated: 17-01-2023 22:07:06
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = false, pref_log_notifications = true, camera_pref_dot = true, pref_date = yyyy.dd.MM HH:mm:ss, pref_biometric_auth = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, pref_exclude_vigilante_from_notifications = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en, pref_log_power = true, mic_pref_bypass_dnd = false, location_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, location_pref_sound = false, location_pref_bypass_dnd = false, camera_pref_sound = true, pref_delete_history = false, mic_pref_sound = true
Default prefs: camera_pref_notifications = false, pref_log_notifications = true, camera_pref_dot = true, pref_date = yyyy.dd.MM HH:mm:ss, pref_biometric_auth = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, pref_exclude_vigilante_from_notifications = true, camera_pref_bypass_dnd = false, mic_pref_notifications = false, pref_language = en, pref_log_power = true, mic_pref_bypass_dnd = false, location_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, location_pref_sound = false, location_pref_bypass_dnd = false, camera_pref_sound = true, pref_delete_history = false, mic_pref_sound = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
hard to reproduce
