### ISSUE TITLE
Camera dot doesn't disappear

### ISSUE THREAD

**Issue by PepperKats** [FunkyMuse/Vigilante#575]
Got all 3 dots turned on, but only the camera dot doesn't disappear. Instead, it just shifts a bit to the right. The dot shifts back to the center when the camera is back on. The dot can only be removed by turning Vigilante off in accessibility and then turning it back on, but the dot will stay stuck on again after the camera turns back on.

My phone has never been rooted and no custom rom

**Comment by FunkyMuse** [comment]
Which phone we're talking about?

**Comment by FunkyMuse** [comment]
Have you tried force stopping Vigilante?

The project hasn't been maintained a while, only dependencies bump.
