### ISSUE TITLE
Onepluis 9: App fails to activate. 

### ISSUE THREAD

**Issue by Uli767** [FunkyMuse/Vigilante#576]
I had to activate the app in my phones settings. 
When I try, I'm told "Restricted setting. For your security, this setting is currently unavailable"

Device is OnePlus 9 pro, latest Oxygen OS (LE2123_11_F.72)

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/512

**Comment by Uli767** [comment]
Didn't see that one. Thx for superfast help :)
