### ISSUE TITLE
It shows that some application is using camera or mic but do not specify which application.

### ISSUE THREAD

**Issue by whois-bogeyman** [FunkyMuse/Vigilante#578]
![Screenshot_2023-02-18-05-40-36-53_ba1161ea5c8f28adb26376b14818c1ab.jpg](https://user-images.githubusercontent.com/26523972/219819722-82e29b57-9d6d-4dd8-bf6c-a0662f55471a.jpg)

**Comment by FunkyMuse** [comment]
Not possible
