### ISSUE TITLE
Crash report #1

### ISSUE THREAD

**Issue by montero4eva** [FunkyMuse/Vigilante#603]
`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at androidx.activity.q.o(Unknown Source:26)
	at x3.j.f(Unknown Source:11)
	at o3.a$a.s(SourceFile:32)
	at y7.a.o(Unknown Source:8)
	at m8.j0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: m8.h0: [t1{Cancelling}@304e6c6, Dispatchers.Main]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 26
Thread time: 0 hr 56 min, 29 sec

`` END of thread info ``

`` Device info ``

Report ID: 57e2941f-49cf-4c6c-9785-0560a2467636
Device ID: 56e005af21e7253f
Application version: 20
Default launcher: com.sec.android.app.launcher
Timezone name: Iran Standard Time
Timezone ID: Asia/Tehran
Version release: 11
Version incremental : A505FDDS9CWA1
Version SDK: 30
Board: exynos9610
Bootloader: A505FDDS9CWA1
Brand: samsung
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: a50
Display: RP1A.200720.012.A505FDDS9CWA1
Fingerprint: samsung/a50dd/a50:11/RP1A.200720.012/A505FDDS9CWA1:user/release-keys
Hardware: exynos9610
Host: VPHLR1014
ID: RP1A.200720.012
Manufacturer: samsung
Product: a50dd
Build time: 1673248474000
Build time formatted: 09-01-2023 10:44:34
Type: user
Radio: A505FXXS9CVL1,A505FXXS9CVL1
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 29
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
Number of CPU cores: 8
Up time with sleep: 157 hr 34 min, 53 sec
Up time without sleep: 90 hr 41 min, 37 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 18-03-2023 12:29:39
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 18-03-2023 00:08:55
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 17-03-2023 23:41:52
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 20
Version name: 1.2.7
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 14-03-2023 17:25:39
Last updated: 14-03-2023 17:25:39
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK, com.crazylegend.vigilante.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: camera_pref_sound = true, camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true
Default prefs: camera_pref_sound = true, camera_pref_notifications = true, camera_pref_bypass_dnd = false, camera_pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/524
