### ISSUE TITLE
[Bug] Vigilante cannot be included in backup

### ISSUE THREAD

**Issue by A-7666** [FunkyMuse/Vigilante#612]
Hello, and thank you very much for the software :-)

There is a bug that doesn't allow backup.

After I run Seedvault, I can see Vigilante present in the "programs that do not allow backup" list.

This is very unfortunate. Could you fix this?

**Comment by FunkyMuse** [comment]
Yes I don't allow backup for security reasons, why would you need a backup, what are you trying to backup?

**Comment by A-7666** [comment]
> what are you trying to backup?

The programs and program data, with Seedvault backup.

> Yes I don't allow backup for security reasons

1. Why? The program doesn't have anything sensitive. What is so bad to backup, settings? This is what I actually want to back up.

2. Don't you think this is disrespectful towards the user - deciding for the user?
On the user's device it is the user who controls it and decides whether he/she need to backup programs and their data/settings or not, and what to backup on my device, not someone else.
The final choice to backup or not is up to the user, and the user should have this choice.

"The user should be presented with the appropriate warnings. However, these are user devices. It should be the user who should have ultimate control over what the device should do and what not"

"Users should have the right to extract all information which was created on, stored on their devices. Even if they have to click through scary warnings. Even if in secure"

Could you fix this?

**Comment by FunkyMuse** [comment]
Backup options can be used against you to extract the data you have.

https://docs.fluidattacks.com/criteria/vulnerabilities/172/

**Comment by A-7666** [comment]
Ehm, Seedvault backup is encrypted and offline! :slightly_smiling_face: 
I don't know what this link is about, maybe about some other tools or cloud tools, dunno, because all AOSPs (Lineage, /e/, Calyx, Graphene, etc) use Seedvault

**Comment by FunkyMuse** [comment]
It's not an issue, it's intended and explained why.
