### ISSUE TITLE
Bug report 2

### ISSUE THREAD

**Issue by wangslangr** [FunkyMuse/Vigilante#621]
`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at androidx.activity.q.o(Unknown Source:26)
	at x3.j.f(Unknown Source:11)
	at o3.a$a.s(SourceFile:32)
	at y7.a.o(Unknown Source:8)
	at m8.j0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: m8.h0: [t1{Cancelling}@fe2042a, Dispatchers.Main]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 34
Thread time: 0 hr 8 min, 12 sec

`` END of thread info ``

`` Device info ``

Report ID: f389d917-ec77-48e1-a50d-802233087f42
Device ID: 549ad4b676246add
Application version: 20
Default launcher: com.teslacoilsw.launcher
Timezone name: Mountain Standard Time
Timezone ID: America/Denver
Version release: 13
Version incremental : R.e4fd2d_7-7000
Version SDK: 33
Board: kona
Bootloader: unknown
Brand: OnePlus
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OnePlus8TTMO
Display: KB2007_11_F.46
Fingerprint: OnePlus/OnePlus8TTMO/OnePlus8TTMO:13/RKQ1.211119.001/R.e4fd2d_7-7000:user/release-keys
Hardware: qcom
Host: dg02-pool03-kvm195
ID: RKQ1.211119.001
Manufacturer: OnePlus
Product: OnePlus8TTMO
Build time: 1676555181000
Build time formatted: 16-02-2023 06:46:21
Type: user
Radio: Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 100
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SM8250
Number of CPU cores: 8
Up time with sleep: 27 hr 4 min, 5 sec
Up time without sleep: 13 hr 46 min, 9 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: 2|K|C:94|M:114
11|J:100
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 03-04-2023 06:54:17
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: 2|K|C:94|M:128
13|J:100
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 03-04-2023 06:53:48
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: 33|K|C:94|M:133
33|J:100
Importance: VISIBLE
Reason: OTHER
Timestamp: 03-04-2023 04:55:48
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 20
Version name: 1.2.7
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 30-03-2023 10:38:30
Last updated: 30-03-2023 10:38:30
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK, com.crazylegend.vigilante.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, pref_delete_history = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/524
