### ISSUE TITLE
At first it was going very well, now It stop recording 

### ISSUE THREAD

**Issue by Dyvol** [FunkyMuse/Vigilante#624]
`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at androidx.activity.l.n(Unknown Source:26)
	at w3.h.f(Unknown Source:11)
	at m3.a$a.r(SourceFile:7)
	at s7.a.v(Unknown Source:8)
	at g8.l0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: g8.j0: [u1{Cancelling}@88c57ec, Dispatchers.Main]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 1
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 34
Thread time: 0 hr 8 min, 3 sec

`` END of thread info ``

`` Device info ``

Report ID: 19b9615a-a6e1-41e2-bbfb-db25a9852fbf
Device ID: 1eb70faee89876da
Application version: 19
Default launcher: com.teslacoilsw.launcher
Timezone name: hora estándar central
Timezone ID: America/Tegucigalpa
Version release: 10
Version incremental : 10.1.0.289C432
Version SDK: 29
Board: HMA
Bootloader: unknown
Brand: HUAWEI
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: HWHMA
Display: HMA-L09 10.1.0.289(C432E8R1P5)
Fingerprint: HUAWEI/HMA-L09/HWHMA:10/HUAWEIHMA-L09/10.1.0.289C432:user/release-keys
Hardware: kirin980
Host: cn-central-1b-fd54bc7601596224378655-1430093079-64fqw
ID: HUAWEIHMA-L09
Manufacturer: HUAWEI
Product: HMA-L09
Build time: 1596228913000
Build time formatted: 31-07-2020 14:55:13
Type: user
Radio: 21C20B379S000C000
Tags: release-keys
User: test
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 88
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: vendor Kirin980
Number of CPU cores: 8
Up time with sleep: 9 hr 40 min, 41 sec
Up time without sleep: 6 hr 51 min, 33 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 19
Version name: 1.2.6
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 12-02-2023 03:09:40
Last updated: 12-02-2023 03:09:40
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = es, pref_log_empty_notifications = true, location_pref_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = false, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = es, pref_log_power = true, mic_pref_sound = false
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = es, pref_log_empty_notifications = true, location_pref_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = false, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = es, pref_log_power = true, mic_pref_sound = false

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/437
