### ISSUE TITLE
Error(IDK what is this)

### ISSUE THREAD

**Issue by Asderlop** [FunkyMuse/Vigilante#634]
`` Stacktrace ``

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{123b898 u0 com.crazylegend.vigilante/.service.VigilanteService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 26
Thread time: 0 hr 0 min, 36 sec

`` END of thread info ``

`` Device info ``

Report ID: 06abe92c-6124-48dc-a6b5-336ae47e0aa8
Device ID: b07658481befc71d
Application version: 20
Default launcher: com.miui.home
Timezone name: Восточная Европа, стандартное время
Timezone ID: Europe/Vilnius
Version release: 11
Version incremental : V12.5.3.0.RGGRUXM
Version SDK: 30
Board: begonia
Bootloader: unknown
Brand: Redmi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: begonia
Display: RP1A.200720.011
Fingerprint: Redmi/begonia_ru/begonia:11/RP1A.200720.011/V12.5.3.0.RGGRUXM:user/release-keys
Hardware: mt6785
Host: m1-xm-ota-bd157.bj.idc.xiaomi.com
ID: RP1A.200720.011
Manufacturer: Xiaomi
Product: begonia_ru
Build time: 1635221177000
Build time formatted: 26-10-2021 07:06:17
Type: user
Radio: MOLY.LR13.R1.TC8.SP.V2.P57,MOLY.LR13.R1.TC8.SP.V2.P57
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 91
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: MT6785V/CC
Number of CPU cores: 8
Up time with sleep: 35 hr 41 min, 59 sec
Up time without sleep: 24 hr 55 min, 30 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: LockScreenClean
Importance: CACHED
Reason: USER_REQUESTED
Timestamp: 22-05-2023 11:14:15
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: null
Importance: CACHED
Reason: LOW_MEMORY
Timestamp: 29-04-2023 17:02:20
`` END of exit reason #2 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 20
Version name: 1.2.7
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 29-04-2023 16:39:39
Last updated: 29-04-2023 16:39:39
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK, com.crazylegend.vigilante.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: pref_exclude_vigilante_from_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false, Locale.Helper.Selected.Language = ru, pref_language = ru
Default prefs: pref_exclude_vigilante_from_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false, Locale.Helper.Selected.Language = ru, pref_language = ru

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Hard to reproduce, goes away on it's own
