### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by jpalcantara** [FunkyMuse/Vigilante#639]
Hello,

  Sorry for this question, I enabled the shortcut to turn on and off Vigilante and now I can not find the stetting to deactivate the float button that is on the screen.

**Comment by jpalcantara** [comment]
Also when a notification comes up is there a way to check the details of the notification.  In this case it just says that it is a "Package installer" in the notification area.

**Comment by FunkyMuse** [comment]
You can always disable it from Settings > Accessibility settings

**Comment by jpalcantara** [comment]
Well in setting I see Info, Custmization, App and security.  No Accessibility settings

**Comment by FunkyMuse** [comment]
Open the Settings on your phone.
Scroll to the section marked Accessibility and tap it.

**Comment by jpalcantara** [comment]
OK!  
And this
Also when a notification comes up is there a way to check the details of the notification. In this case it just says that it is a "Package installer" in the notification area.

**Comment by FunkyMuse** [comment]
No

**Comment by jpalcantara** [comment]
What's the purpose of the notification then?
