### ISSUE TITLE
add AuthorWebSite on fdroid metadata

### ISSUE THREAD

**Issue by jindam-vani** [FunkyMuse/Vigilante#648]
@FunkyMuse 
* **your explicit consent is required** to add AuthorWebSite ```https://funkymuse.dev``` given at https://github.com/FunkyMuse/Vigilante#found-this-repository-useful-%EF%B8%8F in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/com.crazylegend.vigilante.yml)
* on your other two **SubHub** & **Aurora** apps also
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by FunkyMuse** [comment]
You have my consent also remove the donate page, it's not up anymore.
