### ISSUE TITLE
Shutdown 666

### ISSUE THREAD

**Issue by LiLC0de** [FunkyMuse/Vigilante#654]
`` Stacktrace ``

java.lang.RuntimeException: Unable to stop service com.crazylegend.vigilante.service.VigilanteService@4b09baf: java.lang.IllegalArgumentException: View=android.widget.LinearLayout{3a1b61e V.E...... ......I. 0,0-0,0 #7f0a01e2 app:id/root} not attached to window manager
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4858)
	at android.app.ActivityThread.access$2300(ActivityThread.java:275)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.IllegalArgumentException: View=android.widget.LinearLayout{3a1b61e V.E...... ......I. 0,0-0,0 #7f0a01e2 app:id/root} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:538)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:442)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:158)
	at com.crazylegend.vigilante.service.VigilanteService.onDestroy(SourceFile:74)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4838)
	... 9 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 26
Thread time: 0 hr 0 min, 2 sec

`` END of thread info ``

`` Device info ``

Report ID: 046b22ab-ac09-43d9-8129-668854f6dd13
Device ID: 43970a521b6da696
Application version: 20
Default launcher: com.miui.home
Timezone name: Восточная Европа, стандартное время
Timezone ID: Europe/Kiev
Version release: 12
Version incremental : V13.0.2.0.SJCMIXM
Version SDK: 31
Board: galahad
Bootloader: unknown
Brand: Redmi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: galahad
Display: SP1A.210812.016
Fingerprint: Redmi/galahad_global/galahad:12/SP1A.210812.016/V13.0.2.0.SJCMIXM:user/release-keys
Hardware: mt6768
Host: non-pangu-pod-4p6lx
ID: SP1A.210812.016
Manufacturer: Xiaomi
Product: galahad_global
Build time: 1668483532000
Build time formatted: 15-11-2022 05:38:52
Type: user
Radio: MOLY.LR12A.R3.MP.V98.1.P24
Tags: release-keys
User: builder
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 87
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: MT6769T
Number of CPU cores: 8
Up time with sleep: 11 hr 37 min, 38 sec
Up time without sleep: 9 hr 57 min, 22 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: FOREGROUND
Reason: CRASH
Timestamp: 14-06-2023 04:50:57
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: OneKeyClean
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 13-06-2023 21:07:40
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: OneKeyClean
Importance: FOREGROUND_SERVICE
Reason: OTHER
Timestamp: 10-06-2023 16:34:52
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 20
Version name: 1.2.7
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 25-03-2023 15:24:20
Last updated: 25-03-2023 15:24:20
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK, com.crazylegend.vigilante.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
Default prefs: pref_log_notifications = true, camera_pref_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = ru, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = false, pref_biometric_auth = true, location_pref_bypass_dnd = true, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = false, camera_pref_bypass_dnd = true, mic_pref_notifications = true, pref_language = ru, mic_pref_sound = true, pref_log_power = true
Default prefs: pref_log_notifications = true, camera_pref_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = ru, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = false, pref_biometric_auth = true, location_pref_bypass_dnd = true, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = false, camera_pref_bypass_dnd = true, mic_pref_notifications = true, pref_language = ru, mic_pref_sound = true, pref_log_power = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
It's a known issue with Xiaomi, unfortunately I haven't been able to find a fix.
