### ISSUE TITLE
[SOLVED] Phone going off every few seconds

### ISSUE THREAD

**Issue by CStafford-14** [FunkyMuse/Vigilante#70]
I really like the concept of adding a dot letting you know if your camera is being accessed, and I thank you for adding it!

I have a Galaxy S8, and every few seconds while the screen is on, I get a notification that the camera is being used and my dot comes up for the camera as well. Usually, it comes up and disappears in under a second. Since the notification sound plays with the notification, I picked a custom sound just for Vigilante. The sound barely starts before stopping abruptly.

Is this an issue with Vigilante or is my camera being randomly accessed by an application? If the latter, how can I see what app is doing this?

Not sure if this is a bug or if I have some privacy issues.

**EDIT**: On the Galaxy S8, there's a feature called "Smart Stay." Basically, it will check the front camera about 10 seconds before the screen is set to turn off. If it sees your face, it keeps the screen on. If not, it dims the screen. I've noticed that around this 10-second mark, the notification appears, goes away, and the screen dims. This happens every time.

Is there any way I can filter this out?

**Comment by FunkyMuse** [comment]
Glad that you've found the solution, we should start a wiki or add that into the readme for people to know, so is the issue fixed now?

**Comment by CStafford-14** [comment]
I went and disabled the option, so I'm not getting it anymore.Yes, my issue was solved, but I would also suggest adding a filter to filter out certain apps, if possible.On Jan 13, 2021 9:44 AM, FunkyMuse <notifications@github.com> wrote:
Glad that you've found the solution, we should start a wiki or add that into the readme for people to know, so is the issue fixed now?

**Comment by FunkyMuse** [comment]
> I went and disabled the option, so I'm not getting it anymore.Yes, my issue was solved, but I would also suggest adding a filter to filter out certain apps, if possible.On Jan 13, 2021 9:44 AM, FunkyMuse <notifications@github.com> wrote: Glad that you've found the solution, we should start a wiki or add that into the readme for people to know, so is the issue fixed now? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

I'm not sure what you mean by adding a filter, what do you want filtered?

**Comment by CStafford-14** [comment]
By "filter," I mean removing notifications/ detection of certain apps. Basically, prevent me from being notified when Smart Stay is on.On Jan 13, 2021 9:54 AM, FunkyMuse <notifications@github.com> wrote:



I went and disabled the option, so I'm not getting it anymore.Yes, my issue was solved, but I would also suggest adding a filter to filter out certain apps, if possible.On Jan 13, 2021 9:44 AM, FunkyMuse notifications@github.com wrote: Glad that you've found the solution, we should start a wiki or add that into the readme for people to know, so is the issue fixed now? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



I'm not sure what you mean by adding a filter, what do you want filtered?

**Comment by FunkyMuse** [comment]
> By "filter," I mean removing notifications/ detection of certain apps. Basically, prevent me from being notified when Smart Stay is on.On Jan 13, 2021 9:54 AM, FunkyMuse <notifications@github.com> wrote: I went and disabled the option, so I'm not getting it anymore.Yes, my issue was solved, but I would also suggest adding a filter to filter out certain apps, if possible.On Jan 13, 2021 9:44 AM, FunkyMuse notifications@github.com wrote: Glad that you've found the solution, we should start a wiki or add that into the readme for people to know, so is the issue fixed now? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. I'm not sure what you mean by adding a filter, what do you want filtered? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

This is a feature that I don't have time to implement as of now, maybe in the future.
