### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by Sealpupsama** [FunkyMuse/Vigilante#71]
Tried uninstaller, app manager and cleaner master but to no avail. The app can't be uninstall.

Phone:Huawei y6p

**Comment by FunkyMuse** [comment]
Did you install it from f-droid or from GitHub?

**Comment by amilopowers** [comment]
I have installed version 1.0.9 from F-Droid and can't uninstall either.

**Comment by FunkyMuse** [comment]
> I have installed version 1.0.9 from F-Droid and can't uninstall either.

You need to stop the service before you uninstall, if that doesn't work restart your device

**Comment by amilopowers** [comment]
Thanks but this doesn't fix the problem.

**Comment by FunkyMuse** [comment]
> Thanks but this doesn't fix the problem.

I couldn't replicate the bug, sorry everything works fine here, try uninstalling from f-droid too or if that doesn't work from settings

**Comment by amilopowers** [comment]
Here is the solution.
Connect phone to computer.
Get developer rights on the phone
Allow USB debugging
Open a terminal on computer
type "adb devices"
type adb shell pm uninstall -k --user 0 com.crazylegend.vigilante

`amilopowers@amilopowers-xps:~$ adb devices
List of devices attached
ZY2273ZR5H	unauthorized

amilopowers@amilopowers-xps:~$ adb devices
List of devices attached
amilopowers@amilopowers-xps:~$ adb shell pm uninstall -k --user 0 com.crazylegend.vigilante
`

**Comment by kotx** [comment]
> Here is the solution.
> 
> 1. Connect phone to computer.
> 2. Get developer rights on the phone
> 3. Allow USB debugging on phone
> 4. Open a terminal on computer
> 5. type `adb devices`
> 6. type `adb shell pm uninstall -k --user 0 com.crazylegend.vigilante`
> 
> ```
> amilopowers@amilopowers-xps:~$ adb devices
> List of devices attached
> ZY2273ZR5H	unauthorized
> 
> amilopowers@amilopowers-xps:~$ adb devices
> List of devices attached
> amilopowers@amilopowers-xps:~$ adb shell pm uninstall -k --user 0 com.crazylegend.vigilante
> ```

Just a quick note, `pm uninstall ...` can be executed on-device (when rooted) from an elevated terminal (e.g. `su` in Termux) as well.

**Comment by Dirty-dv** [comment]
All you need to do is have a extra SD card. 1st go to app Info and then storage. Swap the app over to the SD card of choice. Once done, just format the SD card. Tada!!!

**Comment by Dirty-dv** [comment]
Oh BTW,  your app. 👍👍👍

**Comment by Bromandaschiznit** [comment]
Really appreciate your answer. By far the easiest method. Again, many Thanks

**Comment by Bromandaschiznit** [comment]
> All you need to do is have a extra SD card. 1st go to app Info and then storage. Swap the app over to the SD card of choice. Once done, just format the SD card. Tada!!!



> All you need to do is have a extra SD card. 1st go to app Info and then storage. Swap the app over to the SD card of choice. Once done, just format the SD card. Tada!!!

[Dirty-dv](https://github.com/Dirty-dv) Really appreciate your answer. By far the easiest method. Again, many Thanks

**Comment by Dirty-dv** [comment]
> > All you need to do is have a extra SD card. 1st go to app Info and then storage. Swap the app over to the SD card of choice. Once done, just format the SD card. Tada!!!
> 
> > All you need to do is have a extra SD card. 1st go to app Info and then storage. Swap the app over to the SD card of choice. Once done, just format the SD card. Tada!!!
> 
> [Dirty-dv](https://github.com/Dirty-dv) Really appreciate your answer. By far the easiest method. Again, many Thanks

**Comment by Dirty-dv** [comment]
@Bromandaschiznit  you are so very welcome. cheers 🍻

**Comment by kubatron** [comment]
This doesn't work ....aby other solution? Android13

**Comment by kubatron** [comment]
This doesn't work ....aby other solution? Android13

Is there any other solution ? I cannot root phone and there is no option to move app to SD card
