### ISSUE TITLE
Camera and Microphone access history are missing

### ISSUE THREAD

**Issue by solarelf** [FunkyMuse/Vigilante#73]
The app has several  history lists, but does not log access history for camera and microphone, yet it throws notifications whenever the app detects camera and mic are accessed. I cannot understand why?

Also, when I tap on the notifications, it does not show which app that triggered it, so little use of it.

**Comment by FunkyMuse** [comment]
It was a removed feature, there was history but you can't get the current app using mic/camera in Android, you can only get the current app that's visible on the screen which sometimes isn't using those permissions at all.

If Google provides us devs with something useful like this, sure, I'll implement it.

**Comment by solarelf** [comment]
I see. Thank you for a quick answer! Sorry fir a double post, there was a glitch when I submitted the first one.

Why I asked? I periodically receive a notification from the app about camera was used, but no dot was displayed (possibly because some hidden service accessed camera for a second so I did not notice). So how do I know which app took my photo?

**Comment by FunkyMuse** [comment]
> I see. Thank you for a quick answer! Sorry fir a double post, there was a glitch when I submitted the first one.
> 
> Why I asked? I periodically receive a notification from the app about camera was used, but no dot was displayed (possibly because some hidden service accessed camera for a second so I did not notice). So how do I know which app took my photo?

No probs.

For the time being you can't know, you can only see when it's used, same thing is on iOS, i was mimicking the behavior and tried to implement the history, it existed but it was unrealistic, sometimes it detected that the laucher was using the camera when the launcher didn't even have permissions, you can't know, sadly.

**Comment by solarelf** [comment]
Thank you for your efforts!
