### ISSUE TITLE
[Enhancement] Option to change permission

### ISSUE THREAD

**Issue by Thewisem** [FunkyMuse/Vigilante#75]
Could you please add the option to change permission for apps when clicking them in the history. Like to remove them,similar to bouncer. Also categorize the apps according to permission in each tab. That last one is optional but first one can you please do.
Thanks

**Comment by FunkyMuse** [comment]
It's not happening anytime soon, I don't have time for this currently, my focus is on other projects, if you like to do so, feel free to make a pull request

Also
https://github.com/FunkyMuse/Vigilante/issues/61
