### ISSUE TITLE
Vigilante doesn't detect when ultra wide and macro mode camera is running. 

### ISSUE THREAD

**Issue by pokegamer5547** [FunkyMuse/Vigilante#78]
I know most apps won't be really using ultra wide or macro but it's still camera so I think vigilante should detect it I guess. But maybe it's a system limitation I guess. My phone. Redmi note 9 pro, android 10 miui 12

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/64
