### ISSUE TITLE
Poor overlapping performance

### ISSUE THREAD

**Issue by solarelf** [FunkyMuse/Vigilante#80]
Hi,

I tested how the app behaves when both camera and mic are used from 2 different apps. I used simple audio recorder and camera app. Whatever app starts first, it displays proper indicator (i set different colors for the dots), but when I start another one, I would expect 2 different dots side-by-side, instead I see the first one displayed.

Note: I set different spacing and size for the dots just to be sure one does not hide behind another.

Only once I witnesses 2 dots side by side, so I assume the app can do this, but for some reason, rarely does. 

![Screenshot_20210116-110827_Camera](https://user-images.githubusercontent.com/42090132/104807950-64806800-57eb-11eb-82b5-08dbb3a44037.jpg)

**Comment by FunkyMuse** [comment]
Please provide a picture of your problem

**Comment by solarelf** [comment]
I added a screenshot. You can see audio is recording and camera is capturing video, but only camera (yellow) dot is there.

Once in a while, ~ 20% of tries, I see it the way it should be:

![Screenshot_20210116-110459_Recorder](https://user-images.githubusercontent.com/42090132/104807993-c640d200-57eb-11eb-90b5-75231cd0999b.jpg)

**Comment by FunkyMuse** [comment]
Is it the same on the phone and not while you're using DEX?

**Comment by FunkyMuse** [comment]
Since it's been 10 days I'm closing the issue due to no feedback
