### ISSUE TITLE
No way to tell, which was the app that triggered it?

### ISSUE THREAD

**Issue by solarelf** [FunkyMuse/Vigilante#85]
Hi,

You say, idea behind the app is to mimic iOS camera and mic detection feature (introduced in iOS14.x), and it really does, but I cannot figure out how I find which was the app that triggered it? In iOS I simply swipe down the screen to open command punkt and the app name is shown just on its top. Nothing like this I found here, is it possible to extract this info from Android somehow?

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/73
