### ISSUE TITLE
Would it support location?

### ISSUE THREAD

**Issue by ahangarha** [FunkyMuse/Vigilante#99]
This is an amazing app. Would it support location also? So that when apps try to access location data, the user gets alerted!

**Comment by FunkyMuse** [comment]
It definitely requires location permission for this feature to work.

But I'm not sure it's gonna detect when the location usage happens.

**Comment by FunkyMuse** [comment]
This isn't coming in the near future.

**Comment by ahangarha** [comment]
I would suggest keeping this issue open as feature request. It is not resolved unless you mean you wont implement it in future as well.

**Comment by pokegamer5547** [comment]
Idk how location can be implemented but it definitely might need internet connection to do such a thing which personally i don't think many people will use it if it gets since accessability is a dangerous permission but we still use with this app without worrying since we know it doesn't require internet and it's source code is open source.

**Comment by FunkyMuse** [comment]
> Idk how location can be implemented but it definitely might need internet connection to do such a thing which personally i don't think many people will use it if it gets since accessability is a dangerous permission but we still use with this app without worrying since we know it doesn't require internet and it's source code is open source.

There's no need for internet connection to access location data but it does require location permission which defies the purpose of the application, but if it's requested and wanted feature and it won't bother people that they give location permission while the app remaining without internet permission, sure.

Maybe there should be a vote

**Comment by pokegamer5547** [comment]
> > Idk how location can be implemented but it definitely might need internet connection to do such a thing which personally i don't think many people will use it if it gets since accessability is a dangerous permission but we still use with this app without worrying since we know it doesn't require internet and it's source code is open source.
> 
> There's no need for internet connection to access location data but it does require location permission which defies the purpose of the application, but if it's requested and wanted feature and it won't bother people that they give location permission while the app remaining without internet permission, sure.
> 
> Maybe there should be a vote

Oh that's true, as long as it doesn't require internet i'm sure people will use it :) i'm not against this feature as  would like to have it too as opt in feature.

**Comment by FunkyMuse** [comment]
It turns out that you can detect whenever there's the GPS in use and Network as well, totally forgot about this and somehow went with my thought about location strictly, so yeah, this feature will come soon, need to think it through how to adapt the change to the current implementation.

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/commit/e397e6a57f0a8f2d014b66cef77ef0cf2f04a415
